// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto
// Protobuf Java Version: 4.32.1

package org.scip_code.scip;

@com.google.protobuf.Generated
public interface MetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scip.Metadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Which version of this protocol was used to generate this index?
   * </pre>
   *
   * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
   * @return The enum numeric value on the wire for version.
   */
  int getVersionValue();
  /**
   * <pre>
   * Which version of this protocol was used to generate this index?
   * </pre>
   *
   * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
   * @return The version.
   */
  org.scip_code.scip.ProtocolVersion getVersion();

  /**
   * <pre>
   * Information about the tool that produced this index.
   * </pre>
   *
   * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
   * @return Whether the toolInfo field is set.
   */
  boolean hasToolInfo();
  /**
   * <pre>
   * Information about the tool that produced this index.
   * </pre>
   *
   * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
   * @return The toolInfo.
   */
  org.scip_code.scip.ToolInfo getToolInfo();
  /**
   * <pre>
   * Information about the tool that produced this index.
   * </pre>
   *
   * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
   */
  org.scip_code.scip.ToolInfoOrBuilder getToolInfoOrBuilder();

  /**
   * <pre>
   * URI-encoded absolute path to the root directory of this index. All
   * documents in this index must appear in a subdirectory of this root
   * directory.
   * </pre>
   *
   * <code>string project_root = 3 [json_name = "projectRoot"];</code>
   * @return The projectRoot.
   */
  java.lang.String getProjectRoot();
  /**
   * <pre>
   * URI-encoded absolute path to the root directory of this index. All
   * documents in this index must appear in a subdirectory of this root
   * directory.
   * </pre>
   *
   * <code>string project_root = 3 [json_name = "projectRoot"];</code>
   * @return The bytes for projectRoot.
   */
  com.google.protobuf.ByteString
      getProjectRootBytes();

  /**
   * <pre>
   * Text encoding of the source files on disk that are referenced from
   * `Document.relative_path`. This value is unrelated to the `Document.text`
   * field, which is a Protobuf string and hence must be UTF-8 encoded.
   * </pre>
   *
   * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
   * @return The enum numeric value on the wire for textDocumentEncoding.
   */
  int getTextDocumentEncodingValue();
  /**
   * <pre>
   * Text encoding of the source files on disk that are referenced from
   * `Document.relative_path`. This value is unrelated to the `Document.text`
   * field, which is a Protobuf string and hence must be UTF-8 encoded.
   * </pre>
   *
   * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
   * @return The textDocumentEncoding.
   */
  org.scip_code.scip.TextEncoding getTextDocumentEncoding();
}
