// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto
// Protobuf Java Version: 4.34.1

package org.scip_code.scip;

@com.google.protobuf.Generated
public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scip.Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The string ID for the programming language this file is written in.
   * The `Language` enum contains the names of most common programming languages.
   * This field is typed as a string to permit any programming language, including
   * ones that are not specified by the `Language` enum.
   * </pre>
   *
   * <code>string language = 4 [json_name = "language"];</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * The string ID for the programming language this file is written in.
   * The `Language` enum contains the names of most common programming languages.
   * This field is typed as a string to permit any programming language, including
   * ones that are not specified by the `Language` enum.
   * </pre>
   *
   * <code>string language = 4 [json_name = "language"];</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * (Required) Unique path to the text document.
   *
   * 1. The path must be relative to the directory supplied in the associated
   * `Metadata.project_root`.
   * 2. The path must not begin with a leading '/'.
   * 3. The path must point to a regular file, not a symbolic link.
   * 4. The path must use '/' as the separator, including on Windows.
   * 5. The path must be canonical; it cannot include empty components ('//'),
   * or '.' or '..'.
   * </pre>
   *
   * <code>string relative_path = 1 [json_name = "relativePath"];</code>
   * @return The relativePath.
   */
  java.lang.String getRelativePath();
  /**
   * <pre>
   * (Required) Unique path to the text document.
   *
   * 1. The path must be relative to the directory supplied in the associated
   * `Metadata.project_root`.
   * 2. The path must not begin with a leading '/'.
   * 3. The path must point to a regular file, not a symbolic link.
   * 4. The path must use '/' as the separator, including on Windows.
   * 5. The path must be canonical; it cannot include empty components ('//'),
   * or '.' or '..'.
   * </pre>
   *
   * <code>string relative_path = 1 [json_name = "relativePath"];</code>
   * @return The bytes for relativePath.
   */
  com.google.protobuf.ByteString
      getRelativePathBytes();

  /**
   * <pre>
   * Occurrences that appear in this file.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  java.util.List<org.scip_code.scip.Occurrence> 
      getOccurrencesList();
  /**
   * <pre>
   * Occurrences that appear in this file.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  org.scip_code.scip.Occurrence getOccurrences(int index);
  /**
   * <pre>
   * Occurrences that appear in this file.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  int getOccurrencesCount();
  /**
   * <pre>
   * Occurrences that appear in this file.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  java.util.List<? extends org.scip_code.scip.OccurrenceOrBuilder> 
      getOccurrencesOrBuilderList();
  /**
   * <pre>
   * Occurrences that appear in this file.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  org.scip_code.scip.OccurrenceOrBuilder getOccurrencesOrBuilder(
      int index);

  /**
   * <pre>
   * Symbols that are "defined" within this document.
   *
   * This should include symbols which technically do not have any definition,
   * but have a reference and are defined by some other symbol (see
   * Relationship.is_definition).
   * </pre>
   *
   * <code>repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];</code>
   */
  java.util.List<org.scip_code.scip.SymbolInformation> 
      getSymbolsList();
  /**
   * <pre>
   * Symbols that are "defined" within this document.
   *
   * This should include symbols which technically do not have any definition,
   * but have a reference and are defined by some other symbol (see
   * Relationship.is_definition).
   * </pre>
   *
   * <code>repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];</code>
   */
  org.scip_code.scip.SymbolInformation getSymbols(int index);
  /**
   * <pre>
   * Symbols that are "defined" within this document.
   *
   * This should include symbols which technically do not have any definition,
   * but have a reference and are defined by some other symbol (see
   * Relationship.is_definition).
   * </pre>
   *
   * <code>repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];</code>
   */
  int getSymbolsCount();
  /**
   * <pre>
   * Symbols that are "defined" within this document.
   *
   * This should include symbols which technically do not have any definition,
   * but have a reference and are defined by some other symbol (see
   * Relationship.is_definition).
   * </pre>
   *
   * <code>repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];</code>
   */
  java.util.List<? extends org.scip_code.scip.SymbolInformationOrBuilder> 
      getSymbolsOrBuilderList();
  /**
   * <pre>
   * Symbols that are "defined" within this document.
   *
   * This should include symbols which technically do not have any definition,
   * but have a reference and are defined by some other symbol (see
   * Relationship.is_definition).
   * </pre>
   *
   * <code>repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];</code>
   */
  org.scip_code.scip.SymbolInformationOrBuilder getSymbolsOrBuilder(
      int index);

  /**
   * <pre>
   * (optional) Text contents of this document. Indexers are not expected to
   * include the text by default. It's preferable that clients read the text
   * contents from the file system by resolving the absolute path from joining
   * `Index.metadata.project_root` and `Document.relative_path`. This field
   * can be useful for testing or when working with virtual/in-memory documents.
   * </pre>
   *
   * <code>string text = 5 [json_name = "text"];</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * (optional) Text contents of this document. Indexers are not expected to
   * include the text by default. It's preferable that clients read the text
   * contents from the file system by resolving the absolute path from joining
   * `Index.metadata.project_root` and `Document.relative_path`. This field
   * can be useful for testing or when working with virtual/in-memory documents.
   * </pre>
   *
   * <code>string text = 5 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * Specifies the encoding used for source ranges in this Document.
   *
   * Usually, this will match the type used to index the string type
   * in the indexer's implementation language in O(1) time.
   * - For an indexer implemented in JVM/.NET language or JavaScript/TypeScript,
   * use UTF16CodeUnitOffsetFromLineStart.
   * - For an indexer implemented in Python,
   * use UTF32CodeUnitOffsetFromLineStart.
   * - For an indexer implemented in Go, Rust or C++,
   * use UTF8ByteOffsetFromLineStart.
   * </pre>
   *
   * <code>.scip.PositionEncoding position_encoding = 6 [json_name = "positionEncoding"];</code>
   * @return The enum numeric value on the wire for positionEncoding.
   */
  int getPositionEncodingValue();
  /**
   * <pre>
   * Specifies the encoding used for source ranges in this Document.
   *
   * Usually, this will match the type used to index the string type
   * in the indexer's implementation language in O(1) time.
   * - For an indexer implemented in JVM/.NET language or JavaScript/TypeScript,
   * use UTF16CodeUnitOffsetFromLineStart.
   * - For an indexer implemented in Python,
   * use UTF32CodeUnitOffsetFromLineStart.
   * - For an indexer implemented in Go, Rust or C++,
   * use UTF8ByteOffsetFromLineStart.
   * </pre>
   *
   * <code>.scip.PositionEncoding position_encoding = 6 [json_name = "positionEncoding"];</code>
   * @return The positionEncoding.
   */
  org.scip_code.scip.PositionEncoding getPositionEncoding();
}
