// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto
// Protobuf Java Version: 4.32.1

package org.scip_code.scip;

/**
 * Protobuf type {@code scip.Metadata}
 */
@com.google.protobuf.Generated
public final class Metadata extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:scip.Metadata)
    MetadataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      Metadata.class.getName());
  }
  // Use Metadata.newBuilder() to construct.
  private Metadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Metadata() {
    version_ = 0;
    projectRoot_ = "";
    textDocumentEncoding_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.scip_code.scip.ScipProto.internal_static_scip_Metadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.scip_code.scip.ScipProto.internal_static_scip_Metadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.scip_code.scip.Metadata.class, org.scip_code.scip.Metadata.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_ = 0;
  /**
   * <pre>
   * Which version of this protocol was used to generate this index?
   * </pre>
   *
   * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
   * @return The enum numeric value on the wire for version.
   */
  @java.lang.Override public int getVersionValue() {
    return version_;
  }
  /**
   * <pre>
   * Which version of this protocol was used to generate this index?
   * </pre>
   *
   * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
   * @return The version.
   */
  @java.lang.Override public org.scip_code.scip.ProtocolVersion getVersion() {
    org.scip_code.scip.ProtocolVersion result = org.scip_code.scip.ProtocolVersion.forNumber(version_);
    return result == null ? org.scip_code.scip.ProtocolVersion.UNRECOGNIZED : result;
  }

  public static final int TOOL_INFO_FIELD_NUMBER = 2;
  private org.scip_code.scip.ToolInfo toolInfo_;
  /**
   * <pre>
   * Information about the tool that produced this index.
   * </pre>
   *
   * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
   * @return Whether the toolInfo field is set.
   */
  @java.lang.Override
  public boolean hasToolInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Information about the tool that produced this index.
   * </pre>
   *
   * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
   * @return The toolInfo.
   */
  @java.lang.Override
  public org.scip_code.scip.ToolInfo getToolInfo() {
    return toolInfo_ == null ? org.scip_code.scip.ToolInfo.getDefaultInstance() : toolInfo_;
  }
  /**
   * <pre>
   * Information about the tool that produced this index.
   * </pre>
   *
   * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
   */
  @java.lang.Override
  public org.scip_code.scip.ToolInfoOrBuilder getToolInfoOrBuilder() {
    return toolInfo_ == null ? org.scip_code.scip.ToolInfo.getDefaultInstance() : toolInfo_;
  }

  public static final int PROJECT_ROOT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object projectRoot_ = "";
  /**
   * <pre>
   * URI-encoded absolute path to the root directory of this index. All
   * documents in this index must appear in a subdirectory of this root
   * directory.
   * </pre>
   *
   * <code>string project_root = 3 [json_name = "projectRoot"];</code>
   * @return The projectRoot.
   */
  @java.lang.Override
  public java.lang.String getProjectRoot() {
    java.lang.Object ref = projectRoot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectRoot_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * URI-encoded absolute path to the root directory of this index. All
   * documents in this index must appear in a subdirectory of this root
   * directory.
   * </pre>
   *
   * <code>string project_root = 3 [json_name = "projectRoot"];</code>
   * @return The bytes for projectRoot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectRootBytes() {
    java.lang.Object ref = projectRoot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectRoot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXT_DOCUMENT_ENCODING_FIELD_NUMBER = 4;
  private int textDocumentEncoding_ = 0;
  /**
   * <pre>
   * Text encoding of the source files on disk that are referenced from
   * `Document.relative_path`. This value is unrelated to the `Document.text`
   * field, which is a Protobuf string and hence must be UTF-8 encoded.
   * </pre>
   *
   * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
   * @return The enum numeric value on the wire for textDocumentEncoding.
   */
  @java.lang.Override public int getTextDocumentEncodingValue() {
    return textDocumentEncoding_;
  }
  /**
   * <pre>
   * Text encoding of the source files on disk that are referenced from
   * `Document.relative_path`. This value is unrelated to the `Document.text`
   * field, which is a Protobuf string and hence must be UTF-8 encoded.
   * </pre>
   *
   * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
   * @return The textDocumentEncoding.
   */
  @java.lang.Override public org.scip_code.scip.TextEncoding getTextDocumentEncoding() {
    org.scip_code.scip.TextEncoding result = org.scip_code.scip.TextEncoding.forNumber(textDocumentEncoding_);
    return result == null ? org.scip_code.scip.TextEncoding.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != org.scip_code.scip.ProtocolVersion.UnspecifiedProtocolVersion.getNumber()) {
      output.writeEnum(1, version_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getToolInfo());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(projectRoot_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, projectRoot_);
    }
    if (textDocumentEncoding_ != org.scip_code.scip.TextEncoding.UnspecifiedTextEncoding.getNumber()) {
      output.writeEnum(4, textDocumentEncoding_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != org.scip_code.scip.ProtocolVersion.UnspecifiedProtocolVersion.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, version_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getToolInfo());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(projectRoot_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, projectRoot_);
    }
    if (textDocumentEncoding_ != org.scip_code.scip.TextEncoding.UnspecifiedTextEncoding.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, textDocumentEncoding_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.scip_code.scip.Metadata)) {
      return super.equals(obj);
    }
    org.scip_code.scip.Metadata other = (org.scip_code.scip.Metadata) obj;

    if (version_ != other.version_) return false;
    if (hasToolInfo() != other.hasToolInfo()) return false;
    if (hasToolInfo()) {
      if (!getToolInfo()
          .equals(other.getToolInfo())) return false;
    }
    if (!getProjectRoot()
        .equals(other.getProjectRoot())) return false;
    if (textDocumentEncoding_ != other.textDocumentEncoding_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + version_;
    if (hasToolInfo()) {
      hash = (37 * hash) + TOOL_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getToolInfo().hashCode();
    }
    hash = (37 * hash) + PROJECT_ROOT_FIELD_NUMBER;
    hash = (53 * hash) + getProjectRoot().hashCode();
    hash = (37 * hash) + TEXT_DOCUMENT_ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + textDocumentEncoding_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.scip_code.scip.Metadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Metadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Metadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Metadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Metadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Metadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Metadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.scip_code.scip.Metadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.scip_code.scip.Metadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.scip_code.scip.Metadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.scip_code.scip.Metadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.scip_code.scip.Metadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.scip_code.scip.Metadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scip.Metadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scip.Metadata)
      org.scip_code.scip.MetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Metadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.scip_code.scip.Metadata.class, org.scip_code.scip.Metadata.Builder.class);
    }

    // Construct using org.scip_code.scip.Metadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetToolInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = 0;
      toolInfo_ = null;
      if (toolInfoBuilder_ != null) {
        toolInfoBuilder_.dispose();
        toolInfoBuilder_ = null;
      }
      projectRoot_ = "";
      textDocumentEncoding_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Metadata_descriptor;
    }

    @java.lang.Override
    public org.scip_code.scip.Metadata getDefaultInstanceForType() {
      return org.scip_code.scip.Metadata.getDefaultInstance();
    }

    @java.lang.Override
    public org.scip_code.scip.Metadata build() {
      org.scip_code.scip.Metadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.scip_code.scip.Metadata buildPartial() {
      org.scip_code.scip.Metadata result = new org.scip_code.scip.Metadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.scip_code.scip.Metadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = version_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.toolInfo_ = toolInfoBuilder_ == null
            ? toolInfo_
            : toolInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.projectRoot_ = projectRoot_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.textDocumentEncoding_ = textDocumentEncoding_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.scip_code.scip.Metadata) {
        return mergeFrom((org.scip_code.scip.Metadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.scip_code.scip.Metadata other) {
      if (other == org.scip_code.scip.Metadata.getDefaultInstance()) return this;
      if (other.version_ != 0) {
        setVersionValue(other.getVersionValue());
      }
      if (other.hasToolInfo()) {
        mergeToolInfo(other.getToolInfo());
      }
      if (!other.getProjectRoot().isEmpty()) {
        projectRoot_ = other.projectRoot_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.textDocumentEncoding_ != 0) {
        setTextDocumentEncodingValue(other.getTextDocumentEncodingValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              version_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetToolInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              projectRoot_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              textDocumentEncoding_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int version_ = 0;
    /**
     * <pre>
     * Which version of this protocol was used to generate this index?
     * </pre>
     *
     * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
     * @return The enum numeric value on the wire for version.
     */
    @java.lang.Override public int getVersionValue() {
      return version_;
    }
    /**
     * <pre>
     * Which version of this protocol was used to generate this index?
     * </pre>
     *
     * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
     * @param value The enum numeric value on the wire for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionValue(int value) {
      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Which version of this protocol was used to generate this index?
     * </pre>
     *
     * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
     * @return The version.
     */
    @java.lang.Override
    public org.scip_code.scip.ProtocolVersion getVersion() {
      org.scip_code.scip.ProtocolVersion result = org.scip_code.scip.ProtocolVersion.forNumber(version_);
      return result == null ? org.scip_code.scip.ProtocolVersion.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Which version of this protocol was used to generate this index?
     * </pre>
     *
     * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(org.scip_code.scip.ProtocolVersion value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      version_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Which version of this protocol was used to generate this index?
     * </pre>
     *
     * <code>.scip.ProtocolVersion version = 1 [json_name = "version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
      onChanged();
      return this;
    }

    private org.scip_code.scip.ToolInfo toolInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        org.scip_code.scip.ToolInfo, org.scip_code.scip.ToolInfo.Builder, org.scip_code.scip.ToolInfoOrBuilder> toolInfoBuilder_;
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     * @return Whether the toolInfo field is set.
     */
    public boolean hasToolInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     * @return The toolInfo.
     */
    public org.scip_code.scip.ToolInfo getToolInfo() {
      if (toolInfoBuilder_ == null) {
        return toolInfo_ == null ? org.scip_code.scip.ToolInfo.getDefaultInstance() : toolInfo_;
      } else {
        return toolInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     */
    public Builder setToolInfo(org.scip_code.scip.ToolInfo value) {
      if (toolInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toolInfo_ = value;
      } else {
        toolInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     */
    public Builder setToolInfo(
        org.scip_code.scip.ToolInfo.Builder builderForValue) {
      if (toolInfoBuilder_ == null) {
        toolInfo_ = builderForValue.build();
      } else {
        toolInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     */
    public Builder mergeToolInfo(org.scip_code.scip.ToolInfo value) {
      if (toolInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          toolInfo_ != null &&
          toolInfo_ != org.scip_code.scip.ToolInfo.getDefaultInstance()) {
          getToolInfoBuilder().mergeFrom(value);
        } else {
          toolInfo_ = value;
        }
      } else {
        toolInfoBuilder_.mergeFrom(value);
      }
      if (toolInfo_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     */
    public Builder clearToolInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      toolInfo_ = null;
      if (toolInfoBuilder_ != null) {
        toolInfoBuilder_.dispose();
        toolInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     */
    public org.scip_code.scip.ToolInfo.Builder getToolInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetToolInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     */
    public org.scip_code.scip.ToolInfoOrBuilder getToolInfoOrBuilder() {
      if (toolInfoBuilder_ != null) {
        return toolInfoBuilder_.getMessageOrBuilder();
      } else {
        return toolInfo_ == null ?
            org.scip_code.scip.ToolInfo.getDefaultInstance() : toolInfo_;
      }
    }
    /**
     * <pre>
     * Information about the tool that produced this index.
     * </pre>
     *
     * <code>.scip.ToolInfo tool_info = 2 [json_name = "toolInfo"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.scip_code.scip.ToolInfo, org.scip_code.scip.ToolInfo.Builder, org.scip_code.scip.ToolInfoOrBuilder> 
        internalGetToolInfoFieldBuilder() {
      if (toolInfoBuilder_ == null) {
        toolInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.scip_code.scip.ToolInfo, org.scip_code.scip.ToolInfo.Builder, org.scip_code.scip.ToolInfoOrBuilder>(
                getToolInfo(),
                getParentForChildren(),
                isClean());
        toolInfo_ = null;
      }
      return toolInfoBuilder_;
    }

    private java.lang.Object projectRoot_ = "";
    /**
     * <pre>
     * URI-encoded absolute path to the root directory of this index. All
     * documents in this index must appear in a subdirectory of this root
     * directory.
     * </pre>
     *
     * <code>string project_root = 3 [json_name = "projectRoot"];</code>
     * @return The projectRoot.
     */
    public java.lang.String getProjectRoot() {
      java.lang.Object ref = projectRoot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectRoot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * URI-encoded absolute path to the root directory of this index. All
     * documents in this index must appear in a subdirectory of this root
     * directory.
     * </pre>
     *
     * <code>string project_root = 3 [json_name = "projectRoot"];</code>
     * @return The bytes for projectRoot.
     */
    public com.google.protobuf.ByteString
        getProjectRootBytes() {
      java.lang.Object ref = projectRoot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectRoot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * URI-encoded absolute path to the root directory of this index. All
     * documents in this index must appear in a subdirectory of this root
     * directory.
     * </pre>
     *
     * <code>string project_root = 3 [json_name = "projectRoot"];</code>
     * @param value The projectRoot to set.
     * @return This builder for chaining.
     */
    public Builder setProjectRoot(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      projectRoot_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URI-encoded absolute path to the root directory of this index. All
     * documents in this index must appear in a subdirectory of this root
     * directory.
     * </pre>
     *
     * <code>string project_root = 3 [json_name = "projectRoot"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectRoot() {
      projectRoot_ = getDefaultInstance().getProjectRoot();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URI-encoded absolute path to the root directory of this index. All
     * documents in this index must appear in a subdirectory of this root
     * directory.
     * </pre>
     *
     * <code>string project_root = 3 [json_name = "projectRoot"];</code>
     * @param value The bytes for projectRoot to set.
     * @return This builder for chaining.
     */
    public Builder setProjectRootBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      projectRoot_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int textDocumentEncoding_ = 0;
    /**
     * <pre>
     * Text encoding of the source files on disk that are referenced from
     * `Document.relative_path`. This value is unrelated to the `Document.text`
     * field, which is a Protobuf string and hence must be UTF-8 encoded.
     * </pre>
     *
     * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
     * @return The enum numeric value on the wire for textDocumentEncoding.
     */
    @java.lang.Override public int getTextDocumentEncodingValue() {
      return textDocumentEncoding_;
    }
    /**
     * <pre>
     * Text encoding of the source files on disk that are referenced from
     * `Document.relative_path`. This value is unrelated to the `Document.text`
     * field, which is a Protobuf string and hence must be UTF-8 encoded.
     * </pre>
     *
     * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
     * @param value The enum numeric value on the wire for textDocumentEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setTextDocumentEncodingValue(int value) {
      textDocumentEncoding_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Text encoding of the source files on disk that are referenced from
     * `Document.relative_path`. This value is unrelated to the `Document.text`
     * field, which is a Protobuf string and hence must be UTF-8 encoded.
     * </pre>
     *
     * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
     * @return The textDocumentEncoding.
     */
    @java.lang.Override
    public org.scip_code.scip.TextEncoding getTextDocumentEncoding() {
      org.scip_code.scip.TextEncoding result = org.scip_code.scip.TextEncoding.forNumber(textDocumentEncoding_);
      return result == null ? org.scip_code.scip.TextEncoding.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Text encoding of the source files on disk that are referenced from
     * `Document.relative_path`. This value is unrelated to the `Document.text`
     * field, which is a Protobuf string and hence must be UTF-8 encoded.
     * </pre>
     *
     * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
     * @param value The textDocumentEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setTextDocumentEncoding(org.scip_code.scip.TextEncoding value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      textDocumentEncoding_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Text encoding of the source files on disk that are referenced from
     * `Document.relative_path`. This value is unrelated to the `Document.text`
     * field, which is a Protobuf string and hence must be UTF-8 encoded.
     * </pre>
     *
     * <code>.scip.TextEncoding text_document_encoding = 4 [json_name = "textDocumentEncoding"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTextDocumentEncoding() {
      bitField0_ = (bitField0_ & ~0x00000008);
      textDocumentEncoding_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:scip.Metadata)
  }

  // @@protoc_insertion_point(class_scope:scip.Metadata)
  private static final org.scip_code.scip.Metadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.scip_code.scip.Metadata();
  }

  public static org.scip_code.scip.Metadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Metadata>
      PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
    @java.lang.Override
    public Metadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Metadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Metadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.scip_code.scip.Metadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

