// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto
// Protobuf Java Version: 4.32.1

package org.scip_code.scip;

@com.google.protobuf.Generated
public interface OccurrenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scip.Occurrence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Half-open [start, end) range of this occurrence. Must be exactly three or four
   * elements:
   *
   * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
   * - Three elements: `[startLine, startCharacter, endCharacter]`. The end line
   * is inferred to have the same value as the start line.
   *
   * It is allowed for the range to be empty (i.e. start==end).
   *
   * Line numbers and characters are always 0-based. Make sure to increment the
   * line/character values before displaying them in an editor-like UI because
   * editors conventionally use 1-based numbers.
   *
   * The 'character' value is interpreted based on the PositionEncoding for
   * the Document.
   *
   * Historical note: the original draft of this schema had a `Range` message
   * type with `start` and `end` fields of type `Position`, mirroring LSP.
   * Benchmarks revealed that this encoding was inefficient and that we could
   * reduce the total payload size of an index by 50% by using `repeated int32`
   * instead. The `repeated int32` encoding is admittedly more embarrassing to
   * work with in some programming languages but we hope the performance
   * improvements make up for it.
   * </pre>
   *
   * <code>repeated int32 range = 1 [json_name = "range"];</code>
   * @return A list containing the range.
   */
  java.util.List<java.lang.Integer> getRangeList();
  /**
   * <pre>
   * Half-open [start, end) range of this occurrence. Must be exactly three or four
   * elements:
   *
   * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
   * - Three elements: `[startLine, startCharacter, endCharacter]`. The end line
   * is inferred to have the same value as the start line.
   *
   * It is allowed for the range to be empty (i.e. start==end).
   *
   * Line numbers and characters are always 0-based. Make sure to increment the
   * line/character values before displaying them in an editor-like UI because
   * editors conventionally use 1-based numbers.
   *
   * The 'character' value is interpreted based on the PositionEncoding for
   * the Document.
   *
   * Historical note: the original draft of this schema had a `Range` message
   * type with `start` and `end` fields of type `Position`, mirroring LSP.
   * Benchmarks revealed that this encoding was inefficient and that we could
   * reduce the total payload size of an index by 50% by using `repeated int32`
   * instead. The `repeated int32` encoding is admittedly more embarrassing to
   * work with in some programming languages but we hope the performance
   * improvements make up for it.
   * </pre>
   *
   * <code>repeated int32 range = 1 [json_name = "range"];</code>
   * @return The count of range.
   */
  int getRangeCount();
  /**
   * <pre>
   * Half-open [start, end) range of this occurrence. Must be exactly three or four
   * elements:
   *
   * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
   * - Three elements: `[startLine, startCharacter, endCharacter]`. The end line
   * is inferred to have the same value as the start line.
   *
   * It is allowed for the range to be empty (i.e. start==end).
   *
   * Line numbers and characters are always 0-based. Make sure to increment the
   * line/character values before displaying them in an editor-like UI because
   * editors conventionally use 1-based numbers.
   *
   * The 'character' value is interpreted based on the PositionEncoding for
   * the Document.
   *
   * Historical note: the original draft of this schema had a `Range` message
   * type with `start` and `end` fields of type `Position`, mirroring LSP.
   * Benchmarks revealed that this encoding was inefficient and that we could
   * reduce the total payload size of an index by 50% by using `repeated int32`
   * instead. The `repeated int32` encoding is admittedly more embarrassing to
   * work with in some programming languages but we hope the performance
   * improvements make up for it.
   * </pre>
   *
   * <code>repeated int32 range = 1 [json_name = "range"];</code>
   * @param index The index of the element to return.
   * @return The range at the given index.
   */
  int getRange(int index);

  /**
   * <pre>
   * (optional) The symbol that appears at this position. See
   * `SymbolInformation.symbol` for how to format symbols as strings.
   * </pre>
   *
   * <code>string symbol = 2 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <pre>
   * (optional) The symbol that appears at this position. See
   * `SymbolInformation.symbol` for how to format symbols as strings.
   * </pre>
   *
   * <code>string symbol = 2 [json_name = "symbol"];</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * (optional) Bitset containing `SymbolRole`s in this occurrence.
   * See `SymbolRole`'s documentation for how to read and write this field.
   * </pre>
   *
   * <code>int32 symbol_roles = 3 [json_name = "symbolRoles"];</code>
   * @return The symbolRoles.
   */
  int getSymbolRoles();

  /**
   * <pre>
   * (optional) CommonMark-formatted documentation for this specific range. If
   * empty, the `Symbol.documentation` field is used instead. One example
   * where this field might be useful is when the symbol represents a generic
   * function (with abstract type parameters such as `List&lt;T&gt;`) and at this
   * occurrence we know the exact values (such as `List&lt;String&gt;`).
   *
   * This field can also be used for dynamically or gradually typed languages,
   * which commonly allow for type-changing assignment.
   * </pre>
   *
   * <code>repeated string override_documentation = 4 [json_name = "overrideDocumentation"];</code>
   * @return A list containing the overrideDocumentation.
   */
  java.util.List<java.lang.String>
      getOverrideDocumentationList();
  /**
   * <pre>
   * (optional) CommonMark-formatted documentation for this specific range. If
   * empty, the `Symbol.documentation` field is used instead. One example
   * where this field might be useful is when the symbol represents a generic
   * function (with abstract type parameters such as `List&lt;T&gt;`) and at this
   * occurrence we know the exact values (such as `List&lt;String&gt;`).
   *
   * This field can also be used for dynamically or gradually typed languages,
   * which commonly allow for type-changing assignment.
   * </pre>
   *
   * <code>repeated string override_documentation = 4 [json_name = "overrideDocumentation"];</code>
   * @return The count of overrideDocumentation.
   */
  int getOverrideDocumentationCount();
  /**
   * <pre>
   * (optional) CommonMark-formatted documentation for this specific range. If
   * empty, the `Symbol.documentation` field is used instead. One example
   * where this field might be useful is when the symbol represents a generic
   * function (with abstract type parameters such as `List&lt;T&gt;`) and at this
   * occurrence we know the exact values (such as `List&lt;String&gt;`).
   *
   * This field can also be used for dynamically or gradually typed languages,
   * which commonly allow for type-changing assignment.
   * </pre>
   *
   * <code>repeated string override_documentation = 4 [json_name = "overrideDocumentation"];</code>
   * @param index The index of the element to return.
   * @return The overrideDocumentation at the given index.
   */
  java.lang.String getOverrideDocumentation(int index);
  /**
   * <pre>
   * (optional) CommonMark-formatted documentation for this specific range. If
   * empty, the `Symbol.documentation` field is used instead. One example
   * where this field might be useful is when the symbol represents a generic
   * function (with abstract type parameters such as `List&lt;T&gt;`) and at this
   * occurrence we know the exact values (such as `List&lt;String&gt;`).
   *
   * This field can also be used for dynamically or gradually typed languages,
   * which commonly allow for type-changing assignment.
   * </pre>
   *
   * <code>repeated string override_documentation = 4 [json_name = "overrideDocumentation"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the overrideDocumentation at the given index.
   */
  com.google.protobuf.ByteString
      getOverrideDocumentationBytes(int index);

  /**
   * <pre>
   * (optional) What syntax highlighting class should be used for this range?
   * </pre>
   *
   * <code>.scip.SyntaxKind syntax_kind = 5 [json_name = "syntaxKind"];</code>
   * @return The enum numeric value on the wire for syntaxKind.
   */
  int getSyntaxKindValue();
  /**
   * <pre>
   * (optional) What syntax highlighting class should be used for this range?
   * </pre>
   *
   * <code>.scip.SyntaxKind syntax_kind = 5 [json_name = "syntaxKind"];</code>
   * @return The syntaxKind.
   */
  org.scip_code.scip.SyntaxKind getSyntaxKind();

  /**
   * <pre>
   * (optional) Diagnostics that have been reported for this specific range.
   * </pre>
   *
   * <code>repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];</code>
   */
  java.util.List<org.scip_code.scip.Diagnostic> 
      getDiagnosticsList();
  /**
   * <pre>
   * (optional) Diagnostics that have been reported for this specific range.
   * </pre>
   *
   * <code>repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];</code>
   */
  org.scip_code.scip.Diagnostic getDiagnostics(int index);
  /**
   * <pre>
   * (optional) Diagnostics that have been reported for this specific range.
   * </pre>
   *
   * <code>repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];</code>
   */
  int getDiagnosticsCount();
  /**
   * <pre>
   * (optional) Diagnostics that have been reported for this specific range.
   * </pre>
   *
   * <code>repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];</code>
   */
  java.util.List<? extends org.scip_code.scip.DiagnosticOrBuilder> 
      getDiagnosticsOrBuilderList();
  /**
   * <pre>
   * (optional) Diagnostics that have been reported for this specific range.
   * </pre>
   *
   * <code>repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];</code>
   */
  org.scip_code.scip.DiagnosticOrBuilder getDiagnosticsOrBuilder(
      int index);

  /**
   * <pre>
   * (optional) Using the same encoding as the sibling `range` field, half-open
   * source range of the nearest non-trivial enclosing AST node. This range must
   * enclose the `range` field. Example applications that make use of the
   * enclosing_range field:
   *
   * - Call hierarchies: to determine what symbols are references from the body
   * of a function
   * - Symbol outline: to display breadcrumbs from the cursor position to the
   * root of the file
   * - Expand selection: to select the nearest enclosing AST node.
   * - Highlight range: to indicate the AST expression that is associated with a
   * hover popover
   *
   * For definition occurrences, the enclosing range should indicate the
   * start/end bounds of the entire definition AST node, including
   * documentation.
   * ```
   * const n = 3
   * ^ range
   * ^^^^^^^^^^^ enclosing_range
   *
   * /&#42;* Parses the string into something *&#47;
   * ^ enclosing_range start --------------------------------------|
   * function parse(input string): string {                        |
   * ^^^^^ range                                          |
   * return input.slice(n)                                     |
   * }                                                             |
   * ^ enclosing_range end &lt;---------------------------------------|
   * ```
   *
   * Any attributes/decorators/attached macros should also be part of the
   * enclosing range.
   *
   * ```python
   * &#64;cache
   * ^ enclosing_range start---------------------|
   * def factorial(n):                           |
   * return n * factorial(n-1) if n else 1   |
   * &lt; enclosing_range end-----------------------|
   *
   * ```
   *
   * For reference occurrences, the enclosing range should indicate the start/end
   * bounds of the parent expression.
   * ```
   * const a = a.b
   * ^ range
   * ^^^ enclosing_range
   * const b = a.b(41).f(42).g(43)
   * ^ range
   * ^^^^^^^^^^^^^ enclosing_range
   * ```
   * </pre>
   *
   * <code>repeated int32 enclosing_range = 7 [json_name = "enclosingRange"];</code>
   * @return A list containing the enclosingRange.
   */
  java.util.List<java.lang.Integer> getEnclosingRangeList();
  /**
   * <pre>
   * (optional) Using the same encoding as the sibling `range` field, half-open
   * source range of the nearest non-trivial enclosing AST node. This range must
   * enclose the `range` field. Example applications that make use of the
   * enclosing_range field:
   *
   * - Call hierarchies: to determine what symbols are references from the body
   * of a function
   * - Symbol outline: to display breadcrumbs from the cursor position to the
   * root of the file
   * - Expand selection: to select the nearest enclosing AST node.
   * - Highlight range: to indicate the AST expression that is associated with a
   * hover popover
   *
   * For definition occurrences, the enclosing range should indicate the
   * start/end bounds of the entire definition AST node, including
   * documentation.
   * ```
   * const n = 3
   * ^ range
   * ^^^^^^^^^^^ enclosing_range
   *
   * /&#42;* Parses the string into something *&#47;
   * ^ enclosing_range start --------------------------------------|
   * function parse(input string): string {                        |
   * ^^^^^ range                                          |
   * return input.slice(n)                                     |
   * }                                                             |
   * ^ enclosing_range end &lt;---------------------------------------|
   * ```
   *
   * Any attributes/decorators/attached macros should also be part of the
   * enclosing range.
   *
   * ```python
   * &#64;cache
   * ^ enclosing_range start---------------------|
   * def factorial(n):                           |
   * return n * factorial(n-1) if n else 1   |
   * &lt; enclosing_range end-----------------------|
   *
   * ```
   *
   * For reference occurrences, the enclosing range should indicate the start/end
   * bounds of the parent expression.
   * ```
   * const a = a.b
   * ^ range
   * ^^^ enclosing_range
   * const b = a.b(41).f(42).g(43)
   * ^ range
   * ^^^^^^^^^^^^^ enclosing_range
   * ```
   * </pre>
   *
   * <code>repeated int32 enclosing_range = 7 [json_name = "enclosingRange"];</code>
   * @return The count of enclosingRange.
   */
  int getEnclosingRangeCount();
  /**
   * <pre>
   * (optional) Using the same encoding as the sibling `range` field, half-open
   * source range of the nearest non-trivial enclosing AST node. This range must
   * enclose the `range` field. Example applications that make use of the
   * enclosing_range field:
   *
   * - Call hierarchies: to determine what symbols are references from the body
   * of a function
   * - Symbol outline: to display breadcrumbs from the cursor position to the
   * root of the file
   * - Expand selection: to select the nearest enclosing AST node.
   * - Highlight range: to indicate the AST expression that is associated with a
   * hover popover
   *
   * For definition occurrences, the enclosing range should indicate the
   * start/end bounds of the entire definition AST node, including
   * documentation.
   * ```
   * const n = 3
   * ^ range
   * ^^^^^^^^^^^ enclosing_range
   *
   * /&#42;* Parses the string into something *&#47;
   * ^ enclosing_range start --------------------------------------|
   * function parse(input string): string {                        |
   * ^^^^^ range                                          |
   * return input.slice(n)                                     |
   * }                                                             |
   * ^ enclosing_range end &lt;---------------------------------------|
   * ```
   *
   * Any attributes/decorators/attached macros should also be part of the
   * enclosing range.
   *
   * ```python
   * &#64;cache
   * ^ enclosing_range start---------------------|
   * def factorial(n):                           |
   * return n * factorial(n-1) if n else 1   |
   * &lt; enclosing_range end-----------------------|
   *
   * ```
   *
   * For reference occurrences, the enclosing range should indicate the start/end
   * bounds of the parent expression.
   * ```
   * const a = a.b
   * ^ range
   * ^^^ enclosing_range
   * const b = a.b(41).f(42).g(43)
   * ^ range
   * ^^^^^^^^^^^^^ enclosing_range
   * ```
   * </pre>
   *
   * <code>repeated int32 enclosing_range = 7 [json_name = "enclosingRange"];</code>
   * @param index The index of the element to return.
   * @return The enclosingRange at the given index.
   */
  int getEnclosingRange(int index);
}
