// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto
// Protobuf Java Version: 4.34.1

package org.scip_code.scip;

/**
 * <pre>
 * Encoding used to interpret the 'character' value in source ranges.
 * </pre>
 *
 * Protobuf enum {@code scip.PositionEncoding}
 */
@com.google.protobuf.Generated
public enum PositionEncoding
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default value. This value should not be used by new SCIP indexers
   * so that a consumer can process the SCIP index without ambiguity.
   * </pre>
   *
   * <code>UnspecifiedPositionEncoding = 0;</code>
   */
  UnspecifiedPositionEncoding(0),
  /**
   * <pre>
   * The 'character' value is interpreted as an offset in terms
   * of UTF-8 code units (i.e. bytes).
   *
   * Example: For the string "🚀 Woo" in UTF-8, the bytes are
   * [240, 159, 154, 128, 32, 87, 111, 111], so the offset for 'W'
   * would be 5.
   * </pre>
   *
   * <code>UTF8CodeUnitOffsetFromLineStart = 1;</code>
   */
  UTF8CodeUnitOffsetFromLineStart(1),
  /**
   * <pre>
   * The 'character' value is interpreted as an offset in terms
   * of UTF-16 code units (each is 2 bytes).
   *
   * Example: For the string "🚀 Woo", the UTF-16 code units are
   * ['&#92;ud83d', '&#92;ude80', ' ', 'W', 'o', 'o'], so the offset for 'W'
   * would be 3.
   * </pre>
   *
   * <code>UTF16CodeUnitOffsetFromLineStart = 2;</code>
   */
  UTF16CodeUnitOffsetFromLineStart(2),
  /**
   * <pre>
   * The 'character' value is interpreted as an offset in terms
   * of UTF-32 code units (each is 4 bytes).
   *
   * Example: For the string "🚀 Woo", the UTF-32 code units are
   * ['🚀', ' ', 'W', 'o', 'o'], so the offset for 'W' would be 2.
   * </pre>
   *
   * <code>UTF32CodeUnitOffsetFromLineStart = 3;</code>
   */
  UTF32CodeUnitOffsetFromLineStart(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "PositionEncoding");
  }
  /**
   * <pre>
   * Default value. This value should not be used by new SCIP indexers
   * so that a consumer can process the SCIP index without ambiguity.
   * </pre>
   *
   * <code>UnspecifiedPositionEncoding = 0;</code>
   */
  public static final int UnspecifiedPositionEncoding_VALUE = 0;
  /**
   * <pre>
   * The 'character' value is interpreted as an offset in terms
   * of UTF-8 code units (i.e. bytes).
   *
   * Example: For the string "🚀 Woo" in UTF-8, the bytes are
   * [240, 159, 154, 128, 32, 87, 111, 111], so the offset for 'W'
   * would be 5.
   * </pre>
   *
   * <code>UTF8CodeUnitOffsetFromLineStart = 1;</code>
   */
  public static final int UTF8CodeUnitOffsetFromLineStart_VALUE = 1;
  /**
   * <pre>
   * The 'character' value is interpreted as an offset in terms
   * of UTF-16 code units (each is 2 bytes).
   *
   * Example: For the string "🚀 Woo", the UTF-16 code units are
   * ['&#92;ud83d', '&#92;ude80', ' ', 'W', 'o', 'o'], so the offset for 'W'
   * would be 3.
   * </pre>
   *
   * <code>UTF16CodeUnitOffsetFromLineStart = 2;</code>
   */
  public static final int UTF16CodeUnitOffsetFromLineStart_VALUE = 2;
  /**
   * <pre>
   * The 'character' value is interpreted as an offset in terms
   * of UTF-32 code units (each is 4 bytes).
   *
   * Example: For the string "🚀 Woo", the UTF-32 code units are
   * ['🚀', ' ', 'W', 'o', 'o'], so the offset for 'W' would be 2.
   * </pre>
   *
   * <code>UTF32CodeUnitOffsetFromLineStart = 3;</code>
   */
  public static final int UTF32CodeUnitOffsetFromLineStart_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PositionEncoding valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PositionEncoding forNumber(int value) {
    switch (value) {
      case 0: return UnspecifiedPositionEncoding;
      case 1: return UTF8CodeUnitOffsetFromLineStart;
      case 2: return UTF16CodeUnitOffsetFromLineStart;
      case 3: return UTF32CodeUnitOffsetFromLineStart;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PositionEncoding>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PositionEncoding> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PositionEncoding>() {
          public PositionEncoding findValueByNumber(int number) {
            return PositionEncoding.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.scip_code.scip.ScipProto.getDescriptor().getEnumType(2);
  }

  private static final PositionEncoding[] VALUES = values();

  public static PositionEncoding valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PositionEncoding(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:scip.PositionEncoding)
}

