// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto
// Protobuf Java Version: 4.32.1

package org.scip_code.scip;

/**
 * Protobuf type {@code scip.Relationship}
 */
@com.google.protobuf.Generated
public final class Relationship extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:scip.Relationship)
    RelationshipOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      Relationship.class.getName());
  }
  // Use Relationship.newBuilder() to construct.
  private Relationship(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Relationship() {
    symbol_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.scip_code.scip.ScipProto.internal_static_scip_Relationship_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.scip_code.scip.ScipProto.internal_static_scip_Relationship_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.scip_code.scip.Relationship.class, org.scip_code.scip.Relationship.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 1 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 1 [json_name = "symbol"];</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_REFERENCE_FIELD_NUMBER = 2;
  private boolean isReference_ = false;
  /**
   * <pre>
   * When resolving "Find references", this field documents what other symbols
   * should be included together with this symbol. For example, consider the
   * following TypeScript code that defines two symbols `Animal#sound()` and
   * `Dog#sound()`:
   * ```ts
   * interface Animal {
   * ^^^^^^ definition Animal#
   * sound(): string
   * ^^^^^ definition Animal#sound()
   * }
   * class Dog implements Animal {
   * ^^^ definition Dog#, relationships = [{symbol: "Animal#", is_implementation: true}]
   * public sound(): string { return "woof" }
   * ^^^^^ definition Dog#sound(), references_symbols = Animal#sound(), relationships = [{symbol: "Animal#sound()", is_implementation:true, is_reference: true}]
   * }
   * const animal: Animal = new Dog()
   * ^^^^^^ reference Animal#
   * console.log(animal.sound())
   * ^^^^^ reference Animal#sound()
   * ```
   * Doing "Find references" on the symbol `Animal#sound()` should return
   * references to the `Dog#sound()` method as well. Vice-versa, doing "Find
   * references" on the `Dog#sound()` method should include references to the
   * `Animal#sound()` method as well.
   * </pre>
   *
   * <code>bool is_reference = 2 [json_name = "isReference"];</code>
   * @return The isReference.
   */
  @java.lang.Override
  public boolean getIsReference() {
    return isReference_;
  }

  public static final int IS_IMPLEMENTATION_FIELD_NUMBER = 3;
  private boolean isImplementation_ = false;
  /**
   * <pre>
   * Similar to `is_reference` but for "Find implementations".
   * It's common for `is_implementation` and `is_reference` to both be true but
   * it's not always the case.
   * In the TypeScript example above, observe that `Dog#` has an
   * `is_implementation` relationship with `"Animal#"` but not `is_reference`.
   * This is because "Find references" on the "Animal#" symbol should not return
   * "Dog#". We only want "Dog#" to return as a result for "Find
   * implementations" on the "Animal#" symbol.
   * </pre>
   *
   * <code>bool is_implementation = 3 [json_name = "isImplementation"];</code>
   * @return The isImplementation.
   */
  @java.lang.Override
  public boolean getIsImplementation() {
    return isImplementation_;
  }

  public static final int IS_TYPE_DEFINITION_FIELD_NUMBER = 4;
  private boolean isTypeDefinition_ = false;
  /**
   * <pre>
   * Similar to `references_symbols` but for "Go to type definition".
   * </pre>
   *
   * <code>bool is_type_definition = 4 [json_name = "isTypeDefinition"];</code>
   * @return The isTypeDefinition.
   */
  @java.lang.Override
  public boolean getIsTypeDefinition() {
    return isTypeDefinition_;
  }

  public static final int IS_DEFINITION_FIELD_NUMBER = 5;
  private boolean isDefinition_ = false;
  /**
   * <pre>
   * Allows overriding the behavior of "Go to definition" and "Find references"
   * for symbols which do not have a definition of their own or could
   * potentially have multiple definitions.
   *
   * For example, in a language with single inheritance and no field overriding,
   * inherited fields can reuse the same symbol as the ancestor which declares
   * the field. In such a situation, is_definition is not needed.
   *
   * On the other hand, in languages with single inheritance and some form
   * of mixins, you can use is_definition to relate the symbol to the
   * matching symbol in ancestor classes, and is_reference to relate the
   * symbol to the matching symbol in mixins.
   * </pre>
   *
   * <code>bool is_definition = 5 [json_name = "isDefinition"];</code>
   * @return The isDefinition.
   */
  @java.lang.Override
  public boolean getIsDefinition() {
    return isDefinition_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, symbol_);
    }
    if (isReference_ != false) {
      output.writeBool(2, isReference_);
    }
    if (isImplementation_ != false) {
      output.writeBool(3, isImplementation_);
    }
    if (isTypeDefinition_ != false) {
      output.writeBool(4, isTypeDefinition_);
    }
    if (isDefinition_ != false) {
      output.writeBool(5, isDefinition_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, symbol_);
    }
    if (isReference_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isReference_);
    }
    if (isImplementation_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isImplementation_);
    }
    if (isTypeDefinition_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isTypeDefinition_);
    }
    if (isDefinition_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isDefinition_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.scip_code.scip.Relationship)) {
      return super.equals(obj);
    }
    org.scip_code.scip.Relationship other = (org.scip_code.scip.Relationship) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (getIsReference()
        != other.getIsReference()) return false;
    if (getIsImplementation()
        != other.getIsImplementation()) return false;
    if (getIsTypeDefinition()
        != other.getIsTypeDefinition()) return false;
    if (getIsDefinition()
        != other.getIsDefinition()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + IS_REFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsReference());
    hash = (37 * hash) + IS_IMPLEMENTATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsImplementation());
    hash = (37 * hash) + IS_TYPE_DEFINITION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsTypeDefinition());
    hash = (37 * hash) + IS_DEFINITION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDefinition());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.scip_code.scip.Relationship parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Relationship parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Relationship parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Relationship parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Relationship parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Relationship parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Relationship parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.scip_code.scip.Relationship parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.scip_code.scip.Relationship parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.scip_code.scip.Relationship parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.scip_code.scip.Relationship parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.scip_code.scip.Relationship parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.scip_code.scip.Relationship prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scip.Relationship}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scip.Relationship)
      org.scip_code.scip.RelationshipOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Relationship_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Relationship_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.scip_code.scip.Relationship.class, org.scip_code.scip.Relationship.Builder.class);
    }

    // Construct using org.scip_code.scip.Relationship.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbol_ = "";
      isReference_ = false;
      isImplementation_ = false;
      isTypeDefinition_ = false;
      isDefinition_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Relationship_descriptor;
    }

    @java.lang.Override
    public org.scip_code.scip.Relationship getDefaultInstanceForType() {
      return org.scip_code.scip.Relationship.getDefaultInstance();
    }

    @java.lang.Override
    public org.scip_code.scip.Relationship build() {
      org.scip_code.scip.Relationship result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.scip_code.scip.Relationship buildPartial() {
      org.scip_code.scip.Relationship result = new org.scip_code.scip.Relationship(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.scip_code.scip.Relationship result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isReference_ = isReference_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isImplementation_ = isImplementation_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isTypeDefinition_ = isTypeDefinition_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isDefinition_ = isDefinition_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.scip_code.scip.Relationship) {
        return mergeFrom((org.scip_code.scip.Relationship)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.scip_code.scip.Relationship other) {
      if (other == org.scip_code.scip.Relationship.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIsReference() != false) {
        setIsReference(other.getIsReference());
      }
      if (other.getIsImplementation() != false) {
        setIsImplementation(other.getIsImplementation());
      }
      if (other.getIsTypeDefinition() != false) {
        setIsTypeDefinition(other.getIsTypeDefinition());
      }
      if (other.getIsDefinition() != false) {
        setIsDefinition(other.getIsDefinition());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isReference_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              isImplementation_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              isTypeDefinition_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              isDefinition_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1 [json_name = "symbol"];</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 1 [json_name = "symbol"];</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 1 [json_name = "symbol"];</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1 [json_name = "symbol"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 1 [json_name = "symbol"];</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean isReference_ ;
    /**
     * <pre>
     * When resolving "Find references", this field documents what other symbols
     * should be included together with this symbol. For example, consider the
     * following TypeScript code that defines two symbols `Animal#sound()` and
     * `Dog#sound()`:
     * ```ts
     * interface Animal {
     * ^^^^^^ definition Animal#
     * sound(): string
     * ^^^^^ definition Animal#sound()
     * }
     * class Dog implements Animal {
     * ^^^ definition Dog#, relationships = [{symbol: "Animal#", is_implementation: true}]
     * public sound(): string { return "woof" }
     * ^^^^^ definition Dog#sound(), references_symbols = Animal#sound(), relationships = [{symbol: "Animal#sound()", is_implementation:true, is_reference: true}]
     * }
     * const animal: Animal = new Dog()
     * ^^^^^^ reference Animal#
     * console.log(animal.sound())
     * ^^^^^ reference Animal#sound()
     * ```
     * Doing "Find references" on the symbol `Animal#sound()` should return
     * references to the `Dog#sound()` method as well. Vice-versa, doing "Find
     * references" on the `Dog#sound()` method should include references to the
     * `Animal#sound()` method as well.
     * </pre>
     *
     * <code>bool is_reference = 2 [json_name = "isReference"];</code>
     * @return The isReference.
     */
    @java.lang.Override
    public boolean getIsReference() {
      return isReference_;
    }
    /**
     * <pre>
     * When resolving "Find references", this field documents what other symbols
     * should be included together with this symbol. For example, consider the
     * following TypeScript code that defines two symbols `Animal#sound()` and
     * `Dog#sound()`:
     * ```ts
     * interface Animal {
     * ^^^^^^ definition Animal#
     * sound(): string
     * ^^^^^ definition Animal#sound()
     * }
     * class Dog implements Animal {
     * ^^^ definition Dog#, relationships = [{symbol: "Animal#", is_implementation: true}]
     * public sound(): string { return "woof" }
     * ^^^^^ definition Dog#sound(), references_symbols = Animal#sound(), relationships = [{symbol: "Animal#sound()", is_implementation:true, is_reference: true}]
     * }
     * const animal: Animal = new Dog()
     * ^^^^^^ reference Animal#
     * console.log(animal.sound())
     * ^^^^^ reference Animal#sound()
     * ```
     * Doing "Find references" on the symbol `Animal#sound()` should return
     * references to the `Dog#sound()` method as well. Vice-versa, doing "Find
     * references" on the `Dog#sound()` method should include references to the
     * `Animal#sound()` method as well.
     * </pre>
     *
     * <code>bool is_reference = 2 [json_name = "isReference"];</code>
     * @param value The isReference to set.
     * @return This builder for chaining.
     */
    public Builder setIsReference(boolean value) {

      isReference_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When resolving "Find references", this field documents what other symbols
     * should be included together with this symbol. For example, consider the
     * following TypeScript code that defines two symbols `Animal#sound()` and
     * `Dog#sound()`:
     * ```ts
     * interface Animal {
     * ^^^^^^ definition Animal#
     * sound(): string
     * ^^^^^ definition Animal#sound()
     * }
     * class Dog implements Animal {
     * ^^^ definition Dog#, relationships = [{symbol: "Animal#", is_implementation: true}]
     * public sound(): string { return "woof" }
     * ^^^^^ definition Dog#sound(), references_symbols = Animal#sound(), relationships = [{symbol: "Animal#sound()", is_implementation:true, is_reference: true}]
     * }
     * const animal: Animal = new Dog()
     * ^^^^^^ reference Animal#
     * console.log(animal.sound())
     * ^^^^^ reference Animal#sound()
     * ```
     * Doing "Find references" on the symbol `Animal#sound()` should return
     * references to the `Dog#sound()` method as well. Vice-versa, doing "Find
     * references" on the `Dog#sound()` method should include references to the
     * `Animal#sound()` method as well.
     * </pre>
     *
     * <code>bool is_reference = 2 [json_name = "isReference"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsReference() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isReference_ = false;
      onChanged();
      return this;
    }

    private boolean isImplementation_ ;
    /**
     * <pre>
     * Similar to `is_reference` but for "Find implementations".
     * It's common for `is_implementation` and `is_reference` to both be true but
     * it's not always the case.
     * In the TypeScript example above, observe that `Dog#` has an
     * `is_implementation` relationship with `"Animal#"` but not `is_reference`.
     * This is because "Find references" on the "Animal#" symbol should not return
     * "Dog#". We only want "Dog#" to return as a result for "Find
     * implementations" on the "Animal#" symbol.
     * </pre>
     *
     * <code>bool is_implementation = 3 [json_name = "isImplementation"];</code>
     * @return The isImplementation.
     */
    @java.lang.Override
    public boolean getIsImplementation() {
      return isImplementation_;
    }
    /**
     * <pre>
     * Similar to `is_reference` but for "Find implementations".
     * It's common for `is_implementation` and `is_reference` to both be true but
     * it's not always the case.
     * In the TypeScript example above, observe that `Dog#` has an
     * `is_implementation` relationship with `"Animal#"` but not `is_reference`.
     * This is because "Find references" on the "Animal#" symbol should not return
     * "Dog#". We only want "Dog#" to return as a result for "Find
     * implementations" on the "Animal#" symbol.
     * </pre>
     *
     * <code>bool is_implementation = 3 [json_name = "isImplementation"];</code>
     * @param value The isImplementation to set.
     * @return This builder for chaining.
     */
    public Builder setIsImplementation(boolean value) {

      isImplementation_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Similar to `is_reference` but for "Find implementations".
     * It's common for `is_implementation` and `is_reference` to both be true but
     * it's not always the case.
     * In the TypeScript example above, observe that `Dog#` has an
     * `is_implementation` relationship with `"Animal#"` but not `is_reference`.
     * This is because "Find references" on the "Animal#" symbol should not return
     * "Dog#". We only want "Dog#" to return as a result for "Find
     * implementations" on the "Animal#" symbol.
     * </pre>
     *
     * <code>bool is_implementation = 3 [json_name = "isImplementation"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsImplementation() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isImplementation_ = false;
      onChanged();
      return this;
    }

    private boolean isTypeDefinition_ ;
    /**
     * <pre>
     * Similar to `references_symbols` but for "Go to type definition".
     * </pre>
     *
     * <code>bool is_type_definition = 4 [json_name = "isTypeDefinition"];</code>
     * @return The isTypeDefinition.
     */
    @java.lang.Override
    public boolean getIsTypeDefinition() {
      return isTypeDefinition_;
    }
    /**
     * <pre>
     * Similar to `references_symbols` but for "Go to type definition".
     * </pre>
     *
     * <code>bool is_type_definition = 4 [json_name = "isTypeDefinition"];</code>
     * @param value The isTypeDefinition to set.
     * @return This builder for chaining.
     */
    public Builder setIsTypeDefinition(boolean value) {

      isTypeDefinition_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Similar to `references_symbols` but for "Go to type definition".
     * </pre>
     *
     * <code>bool is_type_definition = 4 [json_name = "isTypeDefinition"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsTypeDefinition() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isTypeDefinition_ = false;
      onChanged();
      return this;
    }

    private boolean isDefinition_ ;
    /**
     * <pre>
     * Allows overriding the behavior of "Go to definition" and "Find references"
     * for symbols which do not have a definition of their own or could
     * potentially have multiple definitions.
     *
     * For example, in a language with single inheritance and no field overriding,
     * inherited fields can reuse the same symbol as the ancestor which declares
     * the field. In such a situation, is_definition is not needed.
     *
     * On the other hand, in languages with single inheritance and some form
     * of mixins, you can use is_definition to relate the symbol to the
     * matching symbol in ancestor classes, and is_reference to relate the
     * symbol to the matching symbol in mixins.
     * </pre>
     *
     * <code>bool is_definition = 5 [json_name = "isDefinition"];</code>
     * @return The isDefinition.
     */
    @java.lang.Override
    public boolean getIsDefinition() {
      return isDefinition_;
    }
    /**
     * <pre>
     * Allows overriding the behavior of "Go to definition" and "Find references"
     * for symbols which do not have a definition of their own or could
     * potentially have multiple definitions.
     *
     * For example, in a language with single inheritance and no field overriding,
     * inherited fields can reuse the same symbol as the ancestor which declares
     * the field. In such a situation, is_definition is not needed.
     *
     * On the other hand, in languages with single inheritance and some form
     * of mixins, you can use is_definition to relate the symbol to the
     * matching symbol in ancestor classes, and is_reference to relate the
     * symbol to the matching symbol in mixins.
     * </pre>
     *
     * <code>bool is_definition = 5 [json_name = "isDefinition"];</code>
     * @param value The isDefinition to set.
     * @return This builder for chaining.
     */
    public Builder setIsDefinition(boolean value) {

      isDefinition_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Allows overriding the behavior of "Go to definition" and "Find references"
     * for symbols which do not have a definition of their own or could
     * potentially have multiple definitions.
     *
     * For example, in a language with single inheritance and no field overriding,
     * inherited fields can reuse the same symbol as the ancestor which declares
     * the field. In such a situation, is_definition is not needed.
     *
     * On the other hand, in languages with single inheritance and some form
     * of mixins, you can use is_definition to relate the symbol to the
     * matching symbol in ancestor classes, and is_reference to relate the
     * symbol to the matching symbol in mixins.
     * </pre>
     *
     * <code>bool is_definition = 5 [json_name = "isDefinition"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDefinition() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isDefinition_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:scip.Relationship)
  }

  // @@protoc_insertion_point(class_scope:scip.Relationship)
  private static final org.scip_code.scip.Relationship DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.scip_code.scip.Relationship();
  }

  public static org.scip_code.scip.Relationship getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Relationship>
      PARSER = new com.google.protobuf.AbstractParser<Relationship>() {
    @java.lang.Override
    public Relationship parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Relationship> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Relationship> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.scip_code.scip.Relationship getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

