// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto
// Protobuf Java Version: 4.34.1

package org.scip_code.scip;

/**
 * <pre>
 * Signature represents the signature of a symbol as it's displayed in API
 * documentation or hover tooltips. It uses a subset of Document's fields with
 * the same field numbers for wire compatibility with older indexes that encoded
 * signatures using the Document message type.
 * </pre>
 *
 * Protobuf type {@code scip.Signature}
 */
@com.google.protobuf.Generated
public final class Signature extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:scip.Signature)
    SignatureOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Signature");
  }
  // Use Signature.newBuilder() to construct.
  private Signature(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Signature() {
    language_ = "";
    text_ = "";
    occurrences_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.scip_code.scip.ScipProto.internal_static_scip_Signature_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return org.scip_code.scip.ScipProto.internal_static_scip_Signature_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.scip_code.scip.ScipProto.internal_static_scip_Signature_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.scip_code.scip.Signature.class, org.scip_code.scip.Signature.Builder.class);
  }

  public static final int LANGUAGE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object language_ = "";
  /**
   * <pre>
   * The language of the signature, e.g. "java", "go", "python".
   * </pre>
   *
   * <code>string language = 4 [json_name = "language"];</code>
   * @return The language.
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The language of the signature, e.g. "java", "go", "python".
   * </pre>
   *
   * <code>string language = 4 [json_name = "language"];</code>
   * @return The bytes for language.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object text_ = "";
  /**
   * <pre>
   * The text content of the signature, e.g. "void add(int a, int b)".
   * </pre>
   *
   * <code>string text = 5 [json_name = "text"];</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The text content of the signature, e.g. "void add(int a, int b)".
   * </pre>
   *
   * <code>string text = 5 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OCCURRENCES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<org.scip_code.scip.Occurrence> occurrences_;
  /**
   * <pre>
   * (optional) Occurrences within the signature text that reference other
   * symbols, enabling hyperlinking of types in the signature. Ranges are
   * relative to the `text` field.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  @java.lang.Override
  public java.util.List<org.scip_code.scip.Occurrence> getOccurrencesList() {
    return occurrences_;
  }
  /**
   * <pre>
   * (optional) Occurrences within the signature text that reference other
   * symbols, enabling hyperlinking of types in the signature. Ranges are
   * relative to the `text` field.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.scip_code.scip.OccurrenceOrBuilder> 
      getOccurrencesOrBuilderList() {
    return occurrences_;
  }
  /**
   * <pre>
   * (optional) Occurrences within the signature text that reference other
   * symbols, enabling hyperlinking of types in the signature. Ranges are
   * relative to the `text` field.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  @java.lang.Override
  public int getOccurrencesCount() {
    return occurrences_.size();
  }
  /**
   * <pre>
   * (optional) Occurrences within the signature text that reference other
   * symbols, enabling hyperlinking of types in the signature. Ranges are
   * relative to the `text` field.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  @java.lang.Override
  public org.scip_code.scip.Occurrence getOccurrences(int index) {
    return occurrences_.get(index);
  }
  /**
   * <pre>
   * (optional) Occurrences within the signature text that reference other
   * symbols, enabling hyperlinking of types in the signature. Ranges are
   * relative to the `text` field.
   * </pre>
   *
   * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
   */
  @java.lang.Override
  public org.scip_code.scip.OccurrenceOrBuilder getOccurrencesOrBuilder(
      int index) {
    return occurrences_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < occurrences_.size(); i++) {
      output.writeMessage(2, occurrences_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, language_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, text_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = occurrences_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(occurrences_.get(i));
          }
          size += 1 * count;
        }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, language_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, text_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.scip_code.scip.Signature)) {
      return super.equals(obj);
    }
    org.scip_code.scip.Signature other = (org.scip_code.scip.Signature) obj;

    if (!getLanguage()
        .equals(other.getLanguage())) return false;
    if (!getText()
        .equals(other.getText())) return false;
    if (!getOccurrencesList()
        .equals(other.getOccurrencesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    if (getOccurrencesCount() > 0) {
      hash = (37 * hash) + OCCURRENCES_FIELD_NUMBER;
      hash = (53 * hash) + getOccurrencesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.scip_code.scip.Signature parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Signature parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Signature parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Signature parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Signature parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.scip_code.scip.Signature parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.scip_code.scip.Signature parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.scip_code.scip.Signature parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.scip_code.scip.Signature parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.scip_code.scip.Signature parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.scip_code.scip.Signature parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.scip_code.scip.Signature parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.scip_code.scip.Signature prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Signature represents the signature of a symbol as it's displayed in API
   * documentation or hover tooltips. It uses a subset of Document's fields with
   * the same field numbers for wire compatibility with older indexes that encoded
   * signatures using the Document message type.
   * </pre>
   *
   * Protobuf type {@code scip.Signature}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scip.Signature)
      org.scip_code.scip.SignatureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Signature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Signature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.scip_code.scip.Signature.class, org.scip_code.scip.Signature.Builder.class);
    }

    // Construct using org.scip_code.scip.Signature.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      language_ = "";
      text_ = "";
      if (occurrencesBuilder_ == null) {
        occurrences_ = java.util.Collections.emptyList();
      } else {
        occurrences_ = null;
        occurrencesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.scip_code.scip.ScipProto.internal_static_scip_Signature_descriptor;
    }

    @java.lang.Override
    public org.scip_code.scip.Signature getDefaultInstanceForType() {
      return org.scip_code.scip.Signature.getDefaultInstance();
    }

    @java.lang.Override
    public org.scip_code.scip.Signature build() {
      org.scip_code.scip.Signature result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.scip_code.scip.Signature buildPartial() {
      org.scip_code.scip.Signature result = new org.scip_code.scip.Signature(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.scip_code.scip.Signature result) {
      if (occurrencesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          occurrences_ = java.util.Collections.unmodifiableList(occurrences_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.occurrences_ = occurrences_;
      } else {
        result.occurrences_ = occurrencesBuilder_.build();
      }
    }

    private void buildPartial0(org.scip_code.scip.Signature result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.language_ = language_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.text_ = text_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.scip_code.scip.Signature) {
        return mergeFrom((org.scip_code.scip.Signature)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.scip_code.scip.Signature other) {
      if (other == org.scip_code.scip.Signature.getDefaultInstance()) return this;
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (occurrencesBuilder_ == null) {
        if (!other.occurrences_.isEmpty()) {
          if (occurrences_.isEmpty()) {
            occurrences_ = other.occurrences_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureOccurrencesIsMutable();
            occurrences_.addAll(other.occurrences_);
          }
          onChanged();
        }
      } else {
        if (!other.occurrences_.isEmpty()) {
          if (occurrencesBuilder_.isEmpty()) {
            occurrencesBuilder_.dispose();
            occurrencesBuilder_ = null;
            occurrences_ = other.occurrences_;
            bitField0_ = (bitField0_ & ~0x00000004);
            occurrencesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetOccurrencesFieldBuilder() : null;
          } else {
            occurrencesBuilder_.addAllMessages(other.occurrences_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              org.scip_code.scip.Occurrence m =
                  input.readMessage(
                      org.scip_code.scip.Occurrence.parser(),
                      extensionRegistry);
              if (occurrencesBuilder_ == null) {
                ensureOccurrencesIsMutable();
                occurrences_.add(m);
              } else {
                occurrencesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 34: {
              language_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 34
            case 42: {
              text_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object language_ = "";
    /**
     * <pre>
     * The language of the signature, e.g. "java", "go", "python".
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @return The language.
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The language of the signature, e.g. "java", "go", "python".
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @return The bytes for language.
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The language of the signature, e.g. "java", "go", "python".
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      language_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The language of the signature, e.g. "java", "go", "python".
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      language_ = getDefaultInstance().getLanguage();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The language of the signature, e.g. "java", "go", "python".
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @param value The bytes for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      language_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <pre>
     * The text content of the signature, e.g. "void add(int a, int b)".
     * </pre>
     *
     * <code>string text = 5 [json_name = "text"];</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The text content of the signature, e.g. "void add(int a, int b)".
     * </pre>
     *
     * <code>string text = 5 [json_name = "text"];</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The text content of the signature, e.g. "void add(int a, int b)".
     * </pre>
     *
     * <code>string text = 5 [json_name = "text"];</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      text_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The text content of the signature, e.g. "void add(int a, int b)".
     * </pre>
     *
     * <code>string text = 5 [json_name = "text"];</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = getDefaultInstance().getText();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The text content of the signature, e.g. "void add(int a, int b)".
     * </pre>
     *
     * <code>string text = 5 [json_name = "text"];</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      text_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<org.scip_code.scip.Occurrence> occurrences_ =
      java.util.Collections.emptyList();
    private void ensureOccurrencesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        occurrences_ = new java.util.ArrayList<org.scip_code.scip.Occurrence>(occurrences_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.scip_code.scip.Occurrence, org.scip_code.scip.Occurrence.Builder, org.scip_code.scip.OccurrenceOrBuilder> occurrencesBuilder_;

    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public java.util.List<org.scip_code.scip.Occurrence> getOccurrencesList() {
      if (occurrencesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(occurrences_);
      } else {
        return occurrencesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public int getOccurrencesCount() {
      if (occurrencesBuilder_ == null) {
        return occurrences_.size();
      } else {
        return occurrencesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public org.scip_code.scip.Occurrence getOccurrences(int index) {
      if (occurrencesBuilder_ == null) {
        return occurrences_.get(index);
      } else {
        return occurrencesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder setOccurrences(
        int index, org.scip_code.scip.Occurrence value) {
      if (occurrencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOccurrencesIsMutable();
        occurrences_.set(index, value);
        onChanged();
      } else {
        occurrencesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder setOccurrences(
        int index, org.scip_code.scip.Occurrence.Builder builderForValue) {
      if (occurrencesBuilder_ == null) {
        ensureOccurrencesIsMutable();
        occurrences_.set(index, builderForValue.build());
        onChanged();
      } else {
        occurrencesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder addOccurrences(org.scip_code.scip.Occurrence value) {
      if (occurrencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOccurrencesIsMutable();
        occurrences_.add(value);
        onChanged();
      } else {
        occurrencesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder addOccurrences(
        int index, org.scip_code.scip.Occurrence value) {
      if (occurrencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOccurrencesIsMutable();
        occurrences_.add(index, value);
        onChanged();
      } else {
        occurrencesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder addOccurrences(
        org.scip_code.scip.Occurrence.Builder builderForValue) {
      if (occurrencesBuilder_ == null) {
        ensureOccurrencesIsMutable();
        occurrences_.add(builderForValue.build());
        onChanged();
      } else {
        occurrencesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder addOccurrences(
        int index, org.scip_code.scip.Occurrence.Builder builderForValue) {
      if (occurrencesBuilder_ == null) {
        ensureOccurrencesIsMutable();
        occurrences_.add(index, builderForValue.build());
        onChanged();
      } else {
        occurrencesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder addAllOccurrences(
        java.lang.Iterable<? extends org.scip_code.scip.Occurrence> values) {
      if (occurrencesBuilder_ == null) {
        ensureOccurrencesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, occurrences_);
        onChanged();
      } else {
        occurrencesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder clearOccurrences() {
      if (occurrencesBuilder_ == null) {
        occurrences_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        occurrencesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public Builder removeOccurrences(int index) {
      if (occurrencesBuilder_ == null) {
        ensureOccurrencesIsMutable();
        occurrences_.remove(index);
        onChanged();
      } else {
        occurrencesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public org.scip_code.scip.Occurrence.Builder getOccurrencesBuilder(
        int index) {
      return internalGetOccurrencesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public org.scip_code.scip.OccurrenceOrBuilder getOccurrencesOrBuilder(
        int index) {
      if (occurrencesBuilder_ == null) {
        return occurrences_.get(index);  } else {
        return occurrencesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public java.util.List<? extends org.scip_code.scip.OccurrenceOrBuilder> 
         getOccurrencesOrBuilderList() {
      if (occurrencesBuilder_ != null) {
        return occurrencesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(occurrences_);
      }
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public org.scip_code.scip.Occurrence.Builder addOccurrencesBuilder() {
      return internalGetOccurrencesFieldBuilder().addBuilder(
          org.scip_code.scip.Occurrence.getDefaultInstance());
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public org.scip_code.scip.Occurrence.Builder addOccurrencesBuilder(
        int index) {
      return internalGetOccurrencesFieldBuilder().addBuilder(
          index, org.scip_code.scip.Occurrence.getDefaultInstance());
    }
    /**
     * <pre>
     * (optional) Occurrences within the signature text that reference other
     * symbols, enabling hyperlinking of types in the signature. Ranges are
     * relative to the `text` field.
     * </pre>
     *
     * <code>repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];</code>
     */
    public java.util.List<org.scip_code.scip.Occurrence.Builder> 
         getOccurrencesBuilderList() {
      return internalGetOccurrencesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.scip_code.scip.Occurrence, org.scip_code.scip.Occurrence.Builder, org.scip_code.scip.OccurrenceOrBuilder> 
        internalGetOccurrencesFieldBuilder() {
      if (occurrencesBuilder_ == null) {
        occurrencesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.scip_code.scip.Occurrence, org.scip_code.scip.Occurrence.Builder, org.scip_code.scip.OccurrenceOrBuilder>(
                occurrences_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        occurrences_ = null;
      }
      return occurrencesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:scip.Signature)
  }

  // @@protoc_insertion_point(class_scope:scip.Signature)
  private static final org.scip_code.scip.Signature DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.scip_code.scip.Signature();
  }

  public static org.scip_code.scip.Signature getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Signature>
      PARSER = new com.google.protobuf.AbstractParser<Signature>() {
    @java.lang.Override
    public Signature parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Signature> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Signature> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.scip_code.scip.Signature getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

