// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.scip_code.scip

/** Encoding used to interpret the 'character' value in source ranges.
  */
sealed abstract class PositionEncoding(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = org.scip_code.scip.PositionEncoding
  type RecognizedType = org.scip_code.scip.PositionEncoding.Recognized
  def isUnspecifiedPositionEncoding: _root_.scala.Boolean = false
  def isUtf8CodeUnitOffsetFromLineStart: _root_.scala.Boolean = false
  def isUtf16CodeUnitOffsetFromLineStart: _root_.scala.Boolean = false
  def isUtf32CodeUnitOffsetFromLineStart: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[PositionEncoding] = org.scip_code.scip.PositionEncoding
  final def asRecognized: _root_.scala.Option[org.scip_code.scip.PositionEncoding.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[org.scip_code.scip.PositionEncoding.Recognized])
}

object PositionEncoding extends _root_.scalapb.GeneratedEnumCompanion[PositionEncoding] {
  sealed trait Recognized extends PositionEncoding
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[PositionEncoding] = this
  
  /** Default value. This value should not be used by new SCIP indexers
    * so that a consumer can process the SCIP index without ambiguity.
    */
  @SerialVersionUID(0L)
  case object UnspecifiedPositionEncoding extends PositionEncoding(0) with PositionEncoding.Recognized {
    val index = 0
    val name = "UnspecifiedPositionEncoding"
    override def isUnspecifiedPositionEncoding: _root_.scala.Boolean = true
  }
  
  /** The 'character' value is interpreted as an offset in terms
    * of UTF-8 code units (i.e. bytes).
    *
    * Example: For the string "🚀 Woo" in UTF-8, the bytes are
    * [240, 159, 154, 128, 32, 87, 111, 111], so the offset for 'W'
    * would be 5.
    */
  @SerialVersionUID(0L)
  case object UTF8CodeUnitOffsetFromLineStart extends PositionEncoding(1) with PositionEncoding.Recognized {
    val index = 1
    val name = "UTF8CodeUnitOffsetFromLineStart"
    override def isUtf8CodeUnitOffsetFromLineStart: _root_.scala.Boolean = true
  }
  
  /** The 'character' value is interpreted as an offset in terms
    * of UTF-16 code units (each is 2 bytes).
    *
    * Example: For the string "🚀 Woo", the UTF-16 code units are
    * ['&92;ud83d', '&92;ude80', ' ', 'W', 'o', 'o'], so the offset for 'W'
    * would be 3.
    */
  @SerialVersionUID(0L)
  case object UTF16CodeUnitOffsetFromLineStart extends PositionEncoding(2) with PositionEncoding.Recognized {
    val index = 2
    val name = "UTF16CodeUnitOffsetFromLineStart"
    override def isUtf16CodeUnitOffsetFromLineStart: _root_.scala.Boolean = true
  }
  
  /** The 'character' value is interpreted as an offset in terms
    * of UTF-32 code units (each is 4 bytes).
    *
    * Example: For the string "🚀 Woo", the UTF-32 code units are
    * ['🚀', ' ', 'W', 'o', 'o'], so the offset for 'W' would be 2.
    */
  @SerialVersionUID(0L)
  case object UTF32CodeUnitOffsetFromLineStart extends PositionEncoding(3) with PositionEncoding.Recognized {
    val index = 3
    val name = "UTF32CodeUnitOffsetFromLineStart"
    override def isUtf32CodeUnitOffsetFromLineStart: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends PositionEncoding(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(UnspecifiedPositionEncoding, UTF8CodeUnitOffsetFromLineStart, UTF16CodeUnitOffsetFromLineStart, UTF32CodeUnitOffsetFromLineStart)
  def fromValue(__value: _root_.scala.Int): PositionEncoding = __value match {
    case 0 => UnspecifiedPositionEncoding
    case 1 => UTF8CodeUnitOffsetFromLineStart
    case 2 => UTF16CodeUnitOffsetFromLineStart
    case 3 => UTF32CodeUnitOffsetFromLineStart
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = org.scip_code.scip.ScipProto.javaDescriptor.getEnumTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = org.scip_code.scip.ScipProto.scalaDescriptor.enums(2)
}