// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.scip_code.scip

sealed abstract class ProtocolVersion(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = org.scip_code.scip.ProtocolVersion
  type RecognizedType = org.scip_code.scip.ProtocolVersion.Recognized
  def isUnspecifiedProtocolVersion: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ProtocolVersion] = org.scip_code.scip.ProtocolVersion
  final def asRecognized: _root_.scala.Option[org.scip_code.scip.ProtocolVersion.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[org.scip_code.scip.ProtocolVersion.Recognized])
}

object ProtocolVersion extends _root_.scalapb.GeneratedEnumCompanion[ProtocolVersion] {
  sealed trait Recognized extends ProtocolVersion
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ProtocolVersion] = this
  
  @SerialVersionUID(0L)
  case object UnspecifiedProtocolVersion extends ProtocolVersion(0) with ProtocolVersion.Recognized {
    val index = 0
    val name = "UnspecifiedProtocolVersion"
    override def isUnspecifiedProtocolVersion: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends ProtocolVersion(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(UnspecifiedProtocolVersion)
  def fromValue(__value: _root_.scala.Int): ProtocolVersion = __value match {
    case 0 => UnspecifiedProtocolVersion
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = org.scip_code.scip.ScipProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = org.scip_code.scip.ScipProto.scalaDescriptor.enums(0)
}