// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.scip_code.scip

sealed abstract class Severity(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = org.scip_code.scip.Severity
  type RecognizedType = org.scip_code.scip.Severity.Recognized
  def isUnspecifiedSeverity: _root_.scala.Boolean = false
  def isError: _root_.scala.Boolean = false
  def isWarning: _root_.scala.Boolean = false
  def isInformation: _root_.scala.Boolean = false
  def isHint: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[Severity] = org.scip_code.scip.Severity
  final def asRecognized: _root_.scala.Option[org.scip_code.scip.Severity.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[org.scip_code.scip.Severity.Recognized])
}

object Severity extends _root_.scalapb.GeneratedEnumCompanion[Severity] {
  sealed trait Recognized extends Severity
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Severity] = this
  
  @SerialVersionUID(0L)
  case object UnspecifiedSeverity extends Severity(0) with Severity.Recognized {
    val index = 0
    val name = "UnspecifiedSeverity"
    override def isUnspecifiedSeverity: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Error extends Severity(1) with Severity.Recognized {
    val index = 1
    val name = "Error"
    override def isError: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Warning extends Severity(2) with Severity.Recognized {
    val index = 2
    val name = "Warning"
    override def isWarning: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Information extends Severity(3) with Severity.Recognized {
    val index = 3
    val name = "Information"
    override def isInformation: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Hint extends Severity(4) with Severity.Recognized {
    val index = 4
    val name = "Hint"
    override def isHint: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends Severity(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(UnspecifiedSeverity, Error, Warning, Information, Hint)
  def fromValue(__value: _root_.scala.Int): Severity = __value match {
    case 0 => UnspecifiedSeverity
    case 1 => Error
    case 2 => Warning
    case 3 => Information
    case 4 => Hint
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = org.scip_code.scip.ScipProto.javaDescriptor.getEnumTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = org.scip_code.scip.ScipProto.scalaDescriptor.enums(5)
}