// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.scip_code.scip

/** SymbolInformation defines metadata about a symbol, such as the symbol's
  * docstring or what package it's defined it.
  *
  * @param symbol
  *   Identifier of this symbol, which can be referenced from `Occurence.symbol`.
  *   The string must be formatted according to the grammar in `Symbol`.
  * @param documentation
  *   (optional, but strongly recommended) The markdown-formatted documentation
  *   for this symbol. Use `SymbolInformation.signature_documentation` to
  *   document the method/class/type signature of this symbol.
  *   Due to historical reasons, indexers may include signature documentation in
  *   this field by rendering markdown code blocks. New indexers should only
  *   include non-code documentation in this field, for example docstrings.
  * @param relationships
  *   (optional) Relationships to other symbols (e.g., implements, type definition).
  * @param kind
  *   The kind of this symbol. Use this field instead of
  *   `SymbolDescriptor.Suffix` to determine whether something is, for example, a
  *   class or a method.
  * @param displayName
  *   (optional) The name of this symbol as it should be displayed to the user.
  *   For example, the symbol "com/example/MyClass#myMethod(+1)." should have the
  *   display name "myMethod". The `symbol` field is not a reliable source of
  *   the display name for several reasons:
  *  
  *   - Local symbols don't encode the name.
  *   - Some languages have case-insensitive names, so the symbol is all-lowercase.
  *   - The symbol may encode names with special characters that should not be
  *     displayed to the user.
  * @param signatureDocumentation
  *   (optional) The signature of this symbol as it's displayed in API
  *   documentation or in hover tooltips. For example, a Java method that adds
  *   two numbers would have `Signature.language = "java"` and
  *   `Signature.text = "void add(int a, int b)"`. The `language` and `text`
  *   fields are required while `occurrences` can be optionally included to
  *   support hyperlinking referenced symbols in the signature.
  * @param enclosingSymbol
  *   (optional) The enclosing symbol if this is a local symbol.  For non-local
  *   symbols, the enclosing symbol should be parsed from the `symbol` field
  *   using the `Descriptor` grammar.
  *  
  *   The primary use-case for this field is to allow local symbol to be displayed
  *   in a symbol hierarchy for API documentation. It's OK to leave this field
  *   empty for local variables since local variables usually don't belong in API
  *   documentation. However, in the situation that you wish to include a local
  *   symbol in the hierarchy, then you can use `enclosing_symbol` to locate the
  *   "parent" or "owner" of this local symbol. For example, a Java indexer may
  *   choose to use local symbols for private class fields while providing an
  *   `enclosing_symbol` to reference the enclosing class to allow the field to
  *   be part of the class documentation hierarchy. From the perspective of an
  *   author of an indexer, the decision to use a local symbol or global symbol
  *   should exclusively be determined whether the local symbol is accessible
  *   outside the document, not by the capability to find the enclosing
  *   symbol.
  */
@SerialVersionUID(0L)
final case class SymbolInformation(
    symbol: _root_.scala.Predef.String = "",
    documentation: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    relationships: _root_.scala.Seq[org.scip_code.scip.Relationship] = _root_.scala.Seq.empty,
    kind: org.scip_code.scip.SymbolInformation.Kind = org.scip_code.scip.SymbolInformation.Kind.UnspecifiedKind,
    displayName: _root_.scala.Predef.String = "",
    signatureDocumentation: _root_.scala.Option[org.scip_code.scip.Signature] = _root_.scala.None,
    enclosingSymbol: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SymbolInformation] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = symbol
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      documentation.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
      }
      relationships.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = kind.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(5, __value)
        }
      };
      
      {
        val __value = displayName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      if (signatureDocumentation.isDefined) {
        val __value = signatureDocumentation.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = enclosingSymbol
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = symbol
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      documentation.foreach { __v =>
        val __m = __v
        _output__.writeString(3, __m)
      };
      relationships.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = kind.value
        if (__v != 0) {
          _output__.writeEnum(5, __v)
        }
      };
      {
        val __v = displayName
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      signatureDocumentation.foreach { __v =>
        val __m = __v
        _output__.writeTag(7, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = enclosingSymbol
        if (!__v.isEmpty) {
          _output__.writeString(8, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withSymbol(__v: _root_.scala.Predef.String): SymbolInformation = copy(symbol = __v)
    def clearDocumentation = copy(documentation = _root_.scala.Seq.empty)
    def addDocumentation(__vs: _root_.scala.Predef.String *): SymbolInformation = addAllDocumentation(__vs)
    def addAllDocumentation(__vs: Iterable[_root_.scala.Predef.String]): SymbolInformation = copy(documentation = documentation ++ __vs)
    def withDocumentation(__v: _root_.scala.Seq[_root_.scala.Predef.String]): SymbolInformation = copy(documentation = __v)
    def clearRelationships = copy(relationships = _root_.scala.Seq.empty)
    def addRelationships(__vs: org.scip_code.scip.Relationship *): SymbolInformation = addAllRelationships(__vs)
    def addAllRelationships(__vs: Iterable[org.scip_code.scip.Relationship]): SymbolInformation = copy(relationships = relationships ++ __vs)
    def withRelationships(__v: _root_.scala.Seq[org.scip_code.scip.Relationship]): SymbolInformation = copy(relationships = __v)
    def withKind(__v: org.scip_code.scip.SymbolInformation.Kind): SymbolInformation = copy(kind = __v)
    def withDisplayName(__v: _root_.scala.Predef.String): SymbolInformation = copy(displayName = __v)
    def getSignatureDocumentation: org.scip_code.scip.Signature = signatureDocumentation.getOrElse(org.scip_code.scip.Signature.defaultInstance)
    def clearSignatureDocumentation: SymbolInformation = copy(signatureDocumentation = _root_.scala.None)
    def withSignatureDocumentation(__v: org.scip_code.scip.Signature): SymbolInformation = copy(signatureDocumentation = Option(__v))
    def withEnclosingSymbol(__v: _root_.scala.Predef.String): SymbolInformation = copy(enclosingSymbol = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = symbol
          if (__t != "") __t else null
        }
        case 3 => documentation
        case 4 => relationships
        case 5 => {
          val __t = kind.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 6 => {
          val __t = displayName
          if (__t != "") __t else null
        }
        case 7 => signatureDocumentation.orNull
        case 8 => {
          val __t = enclosingSymbol
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(symbol)
        case 3 => _root_.scalapb.descriptors.PRepeated(documentation.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
        case 4 => _root_.scalapb.descriptors.PRepeated(relationships.iterator.map(_.toPMessage).toVector)
        case 5 => _root_.scalapb.descriptors.PEnum(kind.scalaValueDescriptor)
        case 6 => _root_.scalapb.descriptors.PString(displayName)
        case 7 => signatureDocumentation.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 8 => _root_.scalapb.descriptors.PString(enclosingSymbol)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: org.scip_code.scip.SymbolInformation.type = org.scip_code.scip.SymbolInformation
    // @@protoc_insertion_point(GeneratedMessage[scip.SymbolInformation])
}

object SymbolInformation extends scalapb.GeneratedMessageCompanion[org.scip_code.scip.SymbolInformation] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.scip_code.scip.SymbolInformation] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.scip_code.scip.SymbolInformation = {
    var __symbol: _root_.scala.Predef.String = ""
    val __documentation: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    val __relationships: _root_.scala.collection.immutable.VectorBuilder[org.scip_code.scip.Relationship] = new _root_.scala.collection.immutable.VectorBuilder[org.scip_code.scip.Relationship]
    var __kind: org.scip_code.scip.SymbolInformation.Kind = org.scip_code.scip.SymbolInformation.Kind.UnspecifiedKind
    var __displayName: _root_.scala.Predef.String = ""
    var __signatureDocumentation: _root_.scala.Option[org.scip_code.scip.Signature] = _root_.scala.None
    var __enclosingSymbol: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __symbol = _input__.readStringRequireUtf8()
        case 26 =>
          __documentation += _input__.readStringRequireUtf8()
        case 34 =>
          __relationships += _root_.scalapb.LiteParser.readMessage[org.scip_code.scip.Relationship](_input__)
        case 40 =>
          __kind = org.scip_code.scip.SymbolInformation.Kind.fromValue(_input__.readEnum())
        case 50 =>
          __displayName = _input__.readStringRequireUtf8()
        case 58 =>
          __signatureDocumentation = _root_.scala.Option(__signatureDocumentation.fold(_root_.scalapb.LiteParser.readMessage[org.scip_code.scip.Signature](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 66 =>
          __enclosingSymbol = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.scip_code.scip.SymbolInformation(
        symbol = __symbol,
        documentation = __documentation.result(),
        relationships = __relationships.result(),
        kind = __kind,
        displayName = __displayName,
        signatureDocumentation = __signatureDocumentation,
        enclosingSymbol = __enclosingSymbol,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.scip_code.scip.SymbolInformation] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.scip_code.scip.SymbolInformation(
        symbol = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        documentation = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        relationships = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[org.scip_code.scip.Relationship]]).getOrElse(_root_.scala.Seq.empty),
        kind = org.scip_code.scip.SymbolInformation.Kind.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(org.scip_code.scip.SymbolInformation.Kind.UnspecifiedKind.scalaValueDescriptor).number),
        displayName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        signatureDocumentation = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).flatMap(_.as[_root_.scala.Option[org.scip_code.scip.Signature]]),
        enclosingSymbol = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.scip_code.scip.ScipProto.javaDescriptor.getMessageTypes().get(8)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.scip_code.scip.ScipProto.scalaDescriptor.messages(8)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = org.scip_code.scip.Relationship
      case 7 => __out = org.scip_code.scip.Signature
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 5 => org.scip_code.scip.SymbolInformation.Kind
    }
  }
  lazy val defaultInstance = org.scip_code.scip.SymbolInformation(
    symbol = "",
    documentation = _root_.scala.Seq.empty,
    relationships = _root_.scala.Seq.empty,
    kind = org.scip_code.scip.SymbolInformation.Kind.UnspecifiedKind,
    displayName = "",
    signatureDocumentation = _root_.scala.None,
    enclosingSymbol = ""
  )
  /** (optional) Kind represents the fine-grained category of a symbol, suitable for presenting
    * information about the symbol's meaning in the language.
    *
    * For example:
    * - A Java method would have the kind `Method` while a Go function would
    *   have the kind `Function`, even if the symbols for these use the same
    *   syntax for the descriptor `SymbolDescriptor.Suffix.Method`.
    * - A Go struct has the symbol kind `Struct` while a Java class has
    *   the symbol kind `Class` even if they both have the same descriptor:
    *   `SymbolDescriptor.Suffix.Type`.
    *
    * Since Kind is more fine-grained than Suffix:
    * - If two symbols have the same Kind, they should share the same Suffix.
    * - If two symbols have different Suffixes, they should have different Kinds.
    */
  sealed abstract class Kind(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
    type EnumType = org.scip_code.scip.SymbolInformation.Kind
    type RecognizedType = org.scip_code.scip.SymbolInformation.Kind.Recognized
    def isUnspecifiedKind: _root_.scala.Boolean = false
    def isAbstractMethod: _root_.scala.Boolean = false
    def isAccessor: _root_.scala.Boolean = false
    def isArray: _root_.scala.Boolean = false
    def isAssertion: _root_.scala.Boolean = false
    def isAssociatedType: _root_.scala.Boolean = false
    def isAttribute: _root_.scala.Boolean = false
    def isAxiom: _root_.scala.Boolean = false
    def isBoolean: _root_.scala.Boolean = false
    def isClass: _root_.scala.Boolean = false
    def isConcept: _root_.scala.Boolean = false
    def isConstant: _root_.scala.Boolean = false
    def isConstructor: _root_.scala.Boolean = false
    def isContract: _root_.scala.Boolean = false
    def isDataFamily: _root_.scala.Boolean = false
    def isDelegate: _root_.scala.Boolean = false
    def isEnum: _root_.scala.Boolean = false
    def isEnumMember: _root_.scala.Boolean = false
    def isError: _root_.scala.Boolean = false
    def isEvent: _root_.scala.Boolean = false
    def isExtension: _root_.scala.Boolean = false
    def isFact: _root_.scala.Boolean = false
    def isField: _root_.scala.Boolean = false
    def isFile: _root_.scala.Boolean = false
    def isFunction: _root_.scala.Boolean = false
    def isGetter: _root_.scala.Boolean = false
    def isGrammar: _root_.scala.Boolean = false
    def isInstance: _root_.scala.Boolean = false
    def isInterface: _root_.scala.Boolean = false
    def isKey: _root_.scala.Boolean = false
    def isLang: _root_.scala.Boolean = false
    def isLemma: _root_.scala.Boolean = false
    def isLibrary: _root_.scala.Boolean = false
    def isMacro: _root_.scala.Boolean = false
    def isMethod: _root_.scala.Boolean = false
    def isMethodAlias: _root_.scala.Boolean = false
    def isMethodReceiver: _root_.scala.Boolean = false
    def isMethodSpecification: _root_.scala.Boolean = false
    def isMessage: _root_.scala.Boolean = false
    def isMixin: _root_.scala.Boolean = false
    def isModifier: _root_.scala.Boolean = false
    def isModule: _root_.scala.Boolean = false
    def isNamespace: _root_.scala.Boolean = false
    def isNull: _root_.scala.Boolean = false
    def isNumber: _root_.scala.Boolean = false
    def isObject: _root_.scala.Boolean = false
    def isOperator: _root_.scala.Boolean = false
    def isPackage: _root_.scala.Boolean = false
    def isPackageObject: _root_.scala.Boolean = false
    def isParameter: _root_.scala.Boolean = false
    def isParameterLabel: _root_.scala.Boolean = false
    def isPattern: _root_.scala.Boolean = false
    def isPredicate: _root_.scala.Boolean = false
    def isProperty: _root_.scala.Boolean = false
    def isProtocol: _root_.scala.Boolean = false
    def isProtocolMethod: _root_.scala.Boolean = false
    def isPureVirtualMethod: _root_.scala.Boolean = false
    def isQuasiquoter: _root_.scala.Boolean = false
    def isSelfParameter: _root_.scala.Boolean = false
    def isSetter: _root_.scala.Boolean = false
    def isSignature: _root_.scala.Boolean = false
    def isSingletonClass: _root_.scala.Boolean = false
    def isSingletonMethod: _root_.scala.Boolean = false
    def isStaticDataMember: _root_.scala.Boolean = false
    def isStaticEvent: _root_.scala.Boolean = false
    def isStaticField: _root_.scala.Boolean = false
    def isStaticMethod: _root_.scala.Boolean = false
    def isStaticProperty: _root_.scala.Boolean = false
    def isStaticVariable: _root_.scala.Boolean = false
    def isString: _root_.scala.Boolean = false
    def isStruct: _root_.scala.Boolean = false
    def isSubscript: _root_.scala.Boolean = false
    def isTactic: _root_.scala.Boolean = false
    def isTheorem: _root_.scala.Boolean = false
    def isThisParameter: _root_.scala.Boolean = false
    def isTrait: _root_.scala.Boolean = false
    def isTraitMethod: _root_.scala.Boolean = false
    def isType: _root_.scala.Boolean = false
    def isTypeAlias: _root_.scala.Boolean = false
    def isTypeClass: _root_.scala.Boolean = false
    def isTypeClassMethod: _root_.scala.Boolean = false
    def isTypeFamily: _root_.scala.Boolean = false
    def isTypeParameter: _root_.scala.Boolean = false
    def isUnion: _root_.scala.Boolean = false
    def isValue: _root_.scala.Boolean = false
    def isVariable: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[Kind] = org.scip_code.scip.SymbolInformation.Kind
    final def asRecognized: _root_.scala.Option[org.scip_code.scip.SymbolInformation.Kind.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[org.scip_code.scip.SymbolInformation.Kind.Recognized])
  }
  
  object Kind extends _root_.scalapb.GeneratedEnumCompanion[Kind] {
    sealed trait Recognized extends Kind
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Kind] = this
    
    @SerialVersionUID(0L)
    case object UnspecifiedKind extends Kind(0) with Kind.Recognized {
      val index = 0
      val name = "UnspecifiedKind"
      override def isUnspecifiedKind: _root_.scala.Boolean = true
    }
    
    /** A method which may or may not have a body. For Java, Kotlin etc.
      */
    @SerialVersionUID(0L)
    case object AbstractMethod extends Kind(66) with Kind.Recognized {
      val index = 1
      val name = "AbstractMethod"
      override def isAbstractMethod: _root_.scala.Boolean = true
    }
    
    /** For Ruby's attr_accessor
      */
    @SerialVersionUID(0L)
    case object Accessor extends Kind(72) with Kind.Recognized {
      val index = 2
      val name = "Accessor"
      override def isAccessor: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Array extends Kind(1) with Kind.Recognized {
      val index = 3
      val name = "Array"
      override def isArray: _root_.scala.Boolean = true
    }
    
    /** For Alloy
      */
    @SerialVersionUID(0L)
    case object Assertion extends Kind(2) with Kind.Recognized {
      val index = 4
      val name = "Assertion"
      override def isAssertion: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object AssociatedType extends Kind(3) with Kind.Recognized {
      val index = 5
      val name = "AssociatedType"
      override def isAssociatedType: _root_.scala.Boolean = true
    }
    
    /** For C++
      */
    @SerialVersionUID(0L)
    case object Attribute extends Kind(4) with Kind.Recognized {
      val index = 6
      val name = "Attribute"
      override def isAttribute: _root_.scala.Boolean = true
    }
    
    /** For Lean
      */
    @SerialVersionUID(0L)
    case object Axiom extends Kind(5) with Kind.Recognized {
      val index = 7
      val name = "Axiom"
      override def isAxiom: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Boolean extends Kind(6) with Kind.Recognized {
      val index = 8
      val name = "Boolean"
      override def isBoolean: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Class extends Kind(7) with Kind.Recognized {
      val index = 9
      val name = "Class"
      override def isClass: _root_.scala.Boolean = true
    }
    
    /** For C++
      */
    @SerialVersionUID(0L)
    case object Concept extends Kind(86) with Kind.Recognized {
      val index = 10
      val name = "Concept"
      override def isConcept: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Constant extends Kind(8) with Kind.Recognized {
      val index = 11
      val name = "Constant"
      override def isConstant: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Constructor extends Kind(9) with Kind.Recognized {
      val index = 12
      val name = "Constructor"
      override def isConstructor: _root_.scala.Boolean = true
    }
    
    /** For Solidity
      */
    @SerialVersionUID(0L)
    case object Contract extends Kind(62) with Kind.Recognized {
      val index = 13
      val name = "Contract"
      override def isContract: _root_.scala.Boolean = true
    }
    
    /** For Haskell
      */
    @SerialVersionUID(0L)
    case object DataFamily extends Kind(10) with Kind.Recognized {
      val index = 14
      val name = "DataFamily"
      override def isDataFamily: _root_.scala.Boolean = true
    }
    
    /** For C# and F#
      */
    @SerialVersionUID(0L)
    case object Delegate extends Kind(73) with Kind.Recognized {
      val index = 15
      val name = "Delegate"
      override def isDelegate: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Enum extends Kind(11) with Kind.Recognized {
      val index = 16
      val name = "Enum"
      override def isEnum: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object EnumMember extends Kind(12) with Kind.Recognized {
      val index = 17
      val name = "EnumMember"
      override def isEnumMember: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Error extends Kind(63) with Kind.Recognized {
      val index = 18
      val name = "Error"
      override def isError: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Event extends Kind(13) with Kind.Recognized {
      val index = 19
      val name = "Event"
      override def isEvent: _root_.scala.Boolean = true
    }
    
    /** For Dart
      */
    @SerialVersionUID(0L)
    case object Extension extends Kind(84) with Kind.Recognized {
      val index = 20
      val name = "Extension"
      override def isExtension: _root_.scala.Boolean = true
    }
    
    /** For Alloy
      */
    @SerialVersionUID(0L)
    case object Fact extends Kind(14) with Kind.Recognized {
      val index = 21
      val name = "Fact"
      override def isFact: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Field extends Kind(15) with Kind.Recognized {
      val index = 22
      val name = "Field"
      override def isField: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object File extends Kind(16) with Kind.Recognized {
      val index = 23
      val name = "File"
      override def isFile: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Function extends Kind(17) with Kind.Recognized {
      val index = 24
      val name = "Function"
      override def isFunction: _root_.scala.Boolean = true
    }
    
    /** For 'get' in Swift, 'attr_reader' in Ruby
      */
    @SerialVersionUID(0L)
    case object Getter extends Kind(18) with Kind.Recognized {
      val index = 25
      val name = "Getter"
      override def isGetter: _root_.scala.Boolean = true
    }
    
    /** For Raku
      */
    @SerialVersionUID(0L)
    case object Grammar extends Kind(19) with Kind.Recognized {
      val index = 26
      val name = "Grammar"
      override def isGrammar: _root_.scala.Boolean = true
    }
    
    /** For Purescript and Lean
      */
    @SerialVersionUID(0L)
    case object Instance extends Kind(20) with Kind.Recognized {
      val index = 27
      val name = "Instance"
      override def isInstance: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Interface extends Kind(21) with Kind.Recognized {
      val index = 28
      val name = "Interface"
      override def isInterface: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Key extends Kind(22) with Kind.Recognized {
      val index = 29
      val name = "Key"
      override def isKey: _root_.scala.Boolean = true
    }
    
    /** For Racket
      */
    @SerialVersionUID(0L)
    case object Lang extends Kind(23) with Kind.Recognized {
      val index = 30
      val name = "Lang"
      override def isLang: _root_.scala.Boolean = true
    }
    
    /** For Lean
      */
    @SerialVersionUID(0L)
    case object Lemma extends Kind(24) with Kind.Recognized {
      val index = 31
      val name = "Lemma"
      override def isLemma: _root_.scala.Boolean = true
    }
    
    /** For solidity
      */
    @SerialVersionUID(0L)
    case object Library extends Kind(64) with Kind.Recognized {
      val index = 32
      val name = "Library"
      override def isLibrary: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Macro extends Kind(25) with Kind.Recognized {
      val index = 33
      val name = "Macro"
      override def isMacro: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Method extends Kind(26) with Kind.Recognized {
      val index = 34
      val name = "Method"
      override def isMethod: _root_.scala.Boolean = true
    }
    
    /** For Ruby
      */
    @SerialVersionUID(0L)
    case object MethodAlias extends Kind(74) with Kind.Recognized {
      val index = 35
      val name = "MethodAlias"
      override def isMethodAlias: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'ThisParameter' and 'SelfParameter', but for languages
      * like Go where the receiver doesn't have a conventional name.
      */
    @SerialVersionUID(0L)
    case object MethodReceiver extends Kind(27) with Kind.Recognized {
      val index = 36
      val name = "MethodReceiver"
      override def isMethodReceiver: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'AbstractMethod', for Go.
      */
    @SerialVersionUID(0L)
    case object MethodSpecification extends Kind(67) with Kind.Recognized {
      val index = 37
      val name = "MethodSpecification"
      override def isMethodSpecification: _root_.scala.Boolean = true
    }
    
    /** For Protobuf
      */
    @SerialVersionUID(0L)
    case object Message extends Kind(28) with Kind.Recognized {
      val index = 38
      val name = "Message"
      override def isMessage: _root_.scala.Boolean = true
    }
    
    /** For Dart
      */
    @SerialVersionUID(0L)
    case object Mixin extends Kind(85) with Kind.Recognized {
      val index = 39
      val name = "Mixin"
      override def isMixin: _root_.scala.Boolean = true
    }
    
    /** For Solidity
      */
    @SerialVersionUID(0L)
    case object Modifier extends Kind(65) with Kind.Recognized {
      val index = 40
      val name = "Modifier"
      override def isModifier: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Module extends Kind(29) with Kind.Recognized {
      val index = 41
      val name = "Module"
      override def isModule: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Namespace extends Kind(30) with Kind.Recognized {
      val index = 42
      val name = "Namespace"
      override def isNamespace: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Null extends Kind(31) with Kind.Recognized {
      val index = 43
      val name = "Null"
      override def isNull: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Number extends Kind(32) with Kind.Recognized {
      val index = 44
      val name = "Number"
      override def isNumber: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Object extends Kind(33) with Kind.Recognized {
      val index = 45
      val name = "Object"
      override def isObject: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Operator extends Kind(34) with Kind.Recognized {
      val index = 46
      val name = "Operator"
      override def isOperator: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Package extends Kind(35) with Kind.Recognized {
      val index = 47
      val name = "Package"
      override def isPackage: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object PackageObject extends Kind(36) with Kind.Recognized {
      val index = 48
      val name = "PackageObject"
      override def isPackageObject: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Parameter extends Kind(37) with Kind.Recognized {
      val index = 49
      val name = "Parameter"
      override def isParameter: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object ParameterLabel extends Kind(38) with Kind.Recognized {
      val index = 50
      val name = "ParameterLabel"
      override def isParameterLabel: _root_.scala.Boolean = true
    }
    
    /** For Haskell's PatternSynonyms
      */
    @SerialVersionUID(0L)
    case object Pattern extends Kind(39) with Kind.Recognized {
      val index = 51
      val name = "Pattern"
      override def isPattern: _root_.scala.Boolean = true
    }
    
    /** For Alloy
      */
    @SerialVersionUID(0L)
    case object Predicate extends Kind(40) with Kind.Recognized {
      val index = 52
      val name = "Predicate"
      override def isPredicate: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Property extends Kind(41) with Kind.Recognized {
      val index = 53
      val name = "Property"
      override def isProperty: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'Trait' and 'TypeClass', for Swift and Objective-C
      */
    @SerialVersionUID(0L)
    case object Protocol extends Kind(42) with Kind.Recognized {
      val index = 54
      val name = "Protocol"
      override def isProtocol: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'AbstractMethod', for Swift and Objective-C.
      */
    @SerialVersionUID(0L)
    case object ProtocolMethod extends Kind(68) with Kind.Recognized {
      val index = 55
      val name = "ProtocolMethod"
      override def isProtocolMethod: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'AbstractMethod', for C++.
      */
    @SerialVersionUID(0L)
    case object PureVirtualMethod extends Kind(69) with Kind.Recognized {
      val index = 56
      val name = "PureVirtualMethod"
      override def isPureVirtualMethod: _root_.scala.Boolean = true
    }
    
    /** For Haskell
      */
    @SerialVersionUID(0L)
    case object Quasiquoter extends Kind(43) with Kind.Recognized {
      val index = 57
      val name = "Quasiquoter"
      override def isQuasiquoter: _root_.scala.Boolean = true
    }
    
    /** 'self' in Python, Rust, Swift etc.
      */
    @SerialVersionUID(0L)
    case object SelfParameter extends Kind(44) with Kind.Recognized {
      val index = 58
      val name = "SelfParameter"
      override def isSelfParameter: _root_.scala.Boolean = true
    }
    
    /** For 'set' in Swift, 'attr_writer' in Ruby
      */
    @SerialVersionUID(0L)
    case object Setter extends Kind(45) with Kind.Recognized {
      val index = 59
      val name = "Setter"
      override def isSetter: _root_.scala.Boolean = true
    }
    
    /** For Alloy, analogous to 'Struct'.
      */
    @SerialVersionUID(0L)
    case object Signature extends Kind(46) with Kind.Recognized {
      val index = 60
      val name = "Signature"
      override def isSignature: _root_.scala.Boolean = true
    }
    
    /** For Ruby
      */
    @SerialVersionUID(0L)
    case object SingletonClass extends Kind(75) with Kind.Recognized {
      val index = 61
      val name = "SingletonClass"
      override def isSingletonClass: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'StaticMethod', for Ruby.
      */
    @SerialVersionUID(0L)
    case object SingletonMethod extends Kind(76) with Kind.Recognized {
      val index = 62
      val name = "SingletonMethod"
      override def isSingletonMethod: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'StaticField', for C++
      */
    @SerialVersionUID(0L)
    case object StaticDataMember extends Kind(77) with Kind.Recognized {
      val index = 63
      val name = "StaticDataMember"
      override def isStaticDataMember: _root_.scala.Boolean = true
    }
    
    /** For C#
      */
    @SerialVersionUID(0L)
    case object StaticEvent extends Kind(78) with Kind.Recognized {
      val index = 64
      val name = "StaticEvent"
      override def isStaticEvent: _root_.scala.Boolean = true
    }
    
    /** For C#
      */
    @SerialVersionUID(0L)
    case object StaticField extends Kind(79) with Kind.Recognized {
      val index = 65
      val name = "StaticField"
      override def isStaticField: _root_.scala.Boolean = true
    }
    
    /** For Java, C#, C++ etc.
      */
    @SerialVersionUID(0L)
    case object StaticMethod extends Kind(80) with Kind.Recognized {
      val index = 66
      val name = "StaticMethod"
      override def isStaticMethod: _root_.scala.Boolean = true
    }
    
    /** For C#, TypeScript etc.
      */
    @SerialVersionUID(0L)
    case object StaticProperty extends Kind(81) with Kind.Recognized {
      val index = 67
      val name = "StaticProperty"
      override def isStaticProperty: _root_.scala.Boolean = true
    }
    
    /** For C, C++
      */
    @SerialVersionUID(0L)
    case object StaticVariable extends Kind(82) with Kind.Recognized {
      val index = 68
      val name = "StaticVariable"
      override def isStaticVariable: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object String extends Kind(48) with Kind.Recognized {
      val index = 69
      val name = "String"
      override def isString: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Struct extends Kind(49) with Kind.Recognized {
      val index = 70
      val name = "Struct"
      override def isStruct: _root_.scala.Boolean = true
    }
    
    /** For Swift
      */
    @SerialVersionUID(0L)
    case object Subscript extends Kind(47) with Kind.Recognized {
      val index = 71
      val name = "Subscript"
      override def isSubscript: _root_.scala.Boolean = true
    }
    
    /** For Lean
      */
    @SerialVersionUID(0L)
    case object Tactic extends Kind(50) with Kind.Recognized {
      val index = 72
      val name = "Tactic"
      override def isTactic: _root_.scala.Boolean = true
    }
    
    /** For Lean
      */
    @SerialVersionUID(0L)
    case object Theorem extends Kind(51) with Kind.Recognized {
      val index = 73
      val name = "Theorem"
      override def isTheorem: _root_.scala.Boolean = true
    }
    
    /** Method receiver for languages
      * 'this' in JavaScript, C++, Java etc.
      */
    @SerialVersionUID(0L)
    case object ThisParameter extends Kind(52) with Kind.Recognized {
      val index = 74
      val name = "ThisParameter"
      override def isThisParameter: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'Protocol' and 'TypeClass', for Rust, Scala etc.
      */
    @SerialVersionUID(0L)
    case object Trait extends Kind(53) with Kind.Recognized {
      val index = 75
      val name = "Trait"
      override def isTrait: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'AbstractMethod', for Rust, Scala etc.
      */
    @SerialVersionUID(0L)
    case object TraitMethod extends Kind(70) with Kind.Recognized {
      val index = 76
      val name = "TraitMethod"
      override def isTraitMethod: _root_.scala.Boolean = true
    }
    
    /** Data type definition for languages like OCaml which use `type`
      * rather than separate keywords like `struct` and `enum`.
      */
    @SerialVersionUID(0L)
    case object Type extends Kind(54) with Kind.Recognized {
      val index = 77
      val name = "Type"
      override def isType: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object TypeAlias extends Kind(55) with Kind.Recognized {
      val index = 78
      val name = "TypeAlias"
      override def isTypeAlias: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'Trait' and 'Protocol', for Haskell, Purescript etc.
      */
    @SerialVersionUID(0L)
    case object TypeClass extends Kind(56) with Kind.Recognized {
      val index = 79
      val name = "TypeClass"
      override def isTypeClass: _root_.scala.Boolean = true
    }
    
    /** Analogous to 'AbstractMethod', for Haskell, Purescript etc.
      */
    @SerialVersionUID(0L)
    case object TypeClassMethod extends Kind(71) with Kind.Recognized {
      val index = 80
      val name = "TypeClassMethod"
      override def isTypeClassMethod: _root_.scala.Boolean = true
    }
    
    /** For Haskell
      */
    @SerialVersionUID(0L)
    case object TypeFamily extends Kind(57) with Kind.Recognized {
      val index = 81
      val name = "TypeFamily"
      override def isTypeFamily: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object TypeParameter extends Kind(58) with Kind.Recognized {
      val index = 82
      val name = "TypeParameter"
      override def isTypeParameter: _root_.scala.Boolean = true
    }
    
    /** For C, C++, Capn Proto
      */
    @SerialVersionUID(0L)
    case object Union extends Kind(59) with Kind.Recognized {
      val index = 83
      val name = "Union"
      override def isUnion: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object Value extends Kind(60) with Kind.Recognized {
      val index = 84
      val name = "Value"
      override def isValue: _root_.scala.Boolean = true
    }
    
    /** Next = 87;
      * Feel free to open a PR proposing new language-specific kinds.
      */
    @SerialVersionUID(0L)
    case object Variable extends Kind(61) with Kind.Recognized {
      val index = 85
      val name = "Variable"
      override def isVariable: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends Kind(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
    lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(UnspecifiedKind, AbstractMethod, Accessor, Array, Assertion, AssociatedType, Attribute, Axiom, Boolean, Class, Concept, Constant, Constructor, Contract, DataFamily, Delegate, Enum, EnumMember, Error, Event, Extension, Fact, Field, File, Function, Getter, Grammar, Instance, Interface, Key, Lang, Lemma, Library, Macro, Method, MethodAlias, MethodReceiver, MethodSpecification, Message, Mixin, Modifier, Module, Namespace, Null, Number, Object, Operator, Package, PackageObject, Parameter, ParameterLabel, Pattern, Predicate, Property, Protocol, ProtocolMethod, PureVirtualMethod, Quasiquoter, SelfParameter, Setter, Signature, SingletonClass, SingletonMethod, StaticDataMember, StaticEvent, StaticField, StaticMethod, StaticProperty, StaticVariable, String, Struct, Subscript, Tactic, Theorem, ThisParameter, Trait, TraitMethod, Type, TypeAlias, TypeClass, TypeClassMethod, TypeFamily, TypeParameter, Union, Value, Variable)
    def fromValue(__value: _root_.scala.Int): Kind = __value match {
      case 0 => UnspecifiedKind
      case 1 => Array
      case 2 => Assertion
      case 3 => AssociatedType
      case 4 => Attribute
      case 5 => Axiom
      case 6 => Boolean
      case 7 => Class
      case 8 => Constant
      case 9 => Constructor
      case 10 => DataFamily
      case 11 => Enum
      case 12 => EnumMember
      case 13 => Event
      case 14 => Fact
      case 15 => Field
      case 16 => File
      case 17 => Function
      case 18 => Getter
      case 19 => Grammar
      case 20 => Instance
      case 21 => Interface
      case 22 => Key
      case 23 => Lang
      case 24 => Lemma
      case 25 => Macro
      case 26 => Method
      case 27 => MethodReceiver
      case 28 => Message
      case 29 => Module
      case 30 => Namespace
      case 31 => Null
      case 32 => Number
      case 33 => Object
      case 34 => Operator
      case 35 => Package
      case 36 => PackageObject
      case 37 => Parameter
      case 38 => ParameterLabel
      case 39 => Pattern
      case 40 => Predicate
      case 41 => Property
      case 42 => Protocol
      case 43 => Quasiquoter
      case 44 => SelfParameter
      case 45 => Setter
      case 46 => Signature
      case 47 => Subscript
      case 48 => String
      case 49 => Struct
      case 50 => Tactic
      case 51 => Theorem
      case 52 => ThisParameter
      case 53 => Trait
      case 54 => Type
      case 55 => TypeAlias
      case 56 => TypeClass
      case 57 => TypeFamily
      case 58 => TypeParameter
      case 59 => Union
      case 60 => Value
      case 61 => Variable
      case 62 => Contract
      case 63 => Error
      case 64 => Library
      case 65 => Modifier
      case 66 => AbstractMethod
      case 67 => MethodSpecification
      case 68 => ProtocolMethod
      case 69 => PureVirtualMethod
      case 70 => TraitMethod
      case 71 => TypeClassMethod
      case 72 => Accessor
      case 73 => Delegate
      case 74 => MethodAlias
      case 75 => SingletonClass
      case 76 => SingletonMethod
      case 77 => StaticDataMember
      case 78 => StaticEvent
      case 79 => StaticField
      case 80 => StaticMethod
      case 81 => StaticProperty
      case 82 => StaticVariable
      case 84 => Extension
      case 85 => Mixin
      case 86 => Concept
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = org.scip_code.scip.SymbolInformation.javaDescriptor.getEnumTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = org.scip_code.scip.SymbolInformation.scalaDescriptor.enums(0)
  }
  implicit class SymbolInformationLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.scip_code.scip.SymbolInformation]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.scip_code.scip.SymbolInformation](_l) {
    def symbol: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.symbol)((c_, f_) => c_.copy(symbol = f_))
    def documentation: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.documentation)((c_, f_) => c_.copy(documentation = f_))
    def relationships: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[org.scip_code.scip.Relationship]] = field(_.relationships)((c_, f_) => c_.copy(relationships = f_))
    def kind: _root_.scalapb.lenses.Lens[UpperPB, org.scip_code.scip.SymbolInformation.Kind] = field(_.kind)((c_, f_) => c_.copy(kind = f_))
    def displayName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.displayName)((c_, f_) => c_.copy(displayName = f_))
    def signatureDocumentation: _root_.scalapb.lenses.Lens[UpperPB, org.scip_code.scip.Signature] = field(_.getSignatureDocumentation)((c_, f_) => c_.copy(signatureDocumentation = _root_.scala.Option(f_)))
    def optionalSignatureDocumentation: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[org.scip_code.scip.Signature]] = field(_.signatureDocumentation)((c_, f_) => c_.copy(signatureDocumentation = f_))
    def enclosingSymbol: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.enclosingSymbol)((c_, f_) => c_.copy(enclosingSymbol = f_))
  }
  final val SYMBOL_FIELD_NUMBER = 1
  final val DOCUMENTATION_FIELD_NUMBER = 3
  final val RELATIONSHIPS_FIELD_NUMBER = 4
  final val KIND_FIELD_NUMBER = 5
  final val DISPLAY_NAME_FIELD_NUMBER = 6
  final val SIGNATURE_DOCUMENTATION_FIELD_NUMBER = 7
  final val ENCLOSING_SYMBOL_FIELD_NUMBER = 8
  def of(
    symbol: _root_.scala.Predef.String,
    documentation: _root_.scala.Seq[_root_.scala.Predef.String],
    relationships: _root_.scala.Seq[org.scip_code.scip.Relationship],
    kind: org.scip_code.scip.SymbolInformation.Kind,
    displayName: _root_.scala.Predef.String,
    signatureDocumentation: _root_.scala.Option[org.scip_code.scip.Signature],
    enclosingSymbol: _root_.scala.Predef.String
  ): _root_.org.scip_code.scip.SymbolInformation = _root_.org.scip_code.scip.SymbolInformation(
    symbol,
    documentation,
    relationships,
    kind,
    displayName,
    signatureDocumentation,
    enclosingSymbol
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[scip.SymbolInformation])
}
