// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package org.scip_code.scip;

@kotlin.jvm.JvmName("-initializemultiLineRange")
public inline fun multiLineRange(block: org.scip_code.scip.MultiLineRangeKt.Dsl.() -> kotlin.Unit): org.scip_code.scip.MultiLineRange =
  org.scip_code.scip.MultiLineRangeKt.Dsl._create(org.scip_code.scip.MultiLineRange.newBuilder()).apply { block() }._build()
/**
 * ```
 * MultiLineRange represents a half-open [start, end) range spanning multiple lines.
 * ```
 *
 * Protobuf type `scip.MultiLineRange`
 */
public object MultiLineRangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.scip_code.scip.MultiLineRange.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: org.scip_code.scip.MultiLineRange.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): org.scip_code.scip.MultiLineRange = _builder.build()

    /**
     * `int32 start_line = 1 [json_name = "startLine"];`
     */
    public var startLine: kotlin.Int
      @kotlin.jvm.JvmName("getStartLine")
        get() = _builder.startLine
      @kotlin.jvm.JvmName("setStartLine")
        set(value) {
        _builder.startLine = value
      }
    /**
     * `int32 start_line = 1 [json_name = "startLine"];`
     */
    public fun clearStartLine() {
      _builder.clearStartLine()
    }

    /**
     * `int32 start_character = 2 [json_name = "startCharacter"];`
     */
    public var startCharacter: kotlin.Int
      @kotlin.jvm.JvmName("getStartCharacter")
        get() = _builder.startCharacter
      @kotlin.jvm.JvmName("setStartCharacter")
        set(value) {
        _builder.startCharacter = value
      }
    /**
     * `int32 start_character = 2 [json_name = "startCharacter"];`
     */
    public fun clearStartCharacter() {
      _builder.clearStartCharacter()
    }

    /**
     * `int32 end_line = 3 [json_name = "endLine"];`
     */
    public var endLine: kotlin.Int
      @kotlin.jvm.JvmName("getEndLine")
        get() = _builder.endLine
      @kotlin.jvm.JvmName("setEndLine")
        set(value) {
        _builder.endLine = value
      }
    /**
     * `int32 end_line = 3 [json_name = "endLine"];`
     */
    public fun clearEndLine() {
      _builder.clearEndLine()
    }

    /**
     * `int32 end_character = 4 [json_name = "endCharacter"];`
     */
    public var endCharacter: kotlin.Int
      @kotlin.jvm.JvmName("getEndCharacter")
        get() = _builder.endCharacter
      @kotlin.jvm.JvmName("setEndCharacter")
        set(value) {
        _builder.endCharacter = value
      }
    /**
     * `int32 end_character = 4 [json_name = "endCharacter"];`
     */
    public fun clearEndCharacter() {
      _builder.clearEndCharacter()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.scip_code.scip.MultiLineRange.copy(block: `org.scip_code.scip`.MultiLineRangeKt.Dsl.() -> kotlin.Unit): org.scip_code.scip.MultiLineRange =
  `org.scip_code.scip`.MultiLineRangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

