// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package org.scip_code.scip;

@kotlin.jvm.JvmName("-initializeoccurrence")
public inline fun occurrence(block: org.scip_code.scip.OccurrenceKt.Dsl.() -> kotlin.Unit): org.scip_code.scip.Occurrence =
  org.scip_code.scip.OccurrenceKt.Dsl._create(org.scip_code.scip.Occurrence.newBuilder()).apply { block() }._build()
/**
 * ```
 * Occurrence associates a source position with a symbol and/or highlighting
 * information.
 *
 * If possible, indexers should try to bundle logically related information
 * across occurrences into a single occurrence to reduce payload sizes.
 *
 * Range encoding:
 *
 * An Occurrence carries its source range in one of two ways: the deprecated
 * `range` field (a `repeated int32` packed encoding kept for backward
 * compatibility), or one of the typed alternatives in the `typed_range`
 * oneof. New producers SHOULD set `typed_range` and SHOULD NOT set the
 * deprecated `range` field. The same rule applies to `enclosing_range` and
 * `typed_enclosing_range`.
 *
 * When both encodings are present on the same Occurrence, `typed_range` takes
 * precedence over `range` (likewise `typed_enclosing_range` over
 * `enclosing_range`). Producers that set both forms MUST keep them
 * semantically equivalent. Consumers SHOULD prefer the typed form when
 * available and fall back to the `repeated int32` form otherwise.
 * ```
 *
 * Protobuf type `scip.Occurrence`
 */
public object OccurrenceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.scip_code.scip.Occurrence.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: org.scip_code.scip.Occurrence.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): org.scip_code.scip.Occurrence = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RangeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Deprecated: Use `single_line_range` or `multi_line_range` instead.
     *
     * Half-open [start, end) range. Must be exactly three or four elements:
     * - Three elements: `[startLine, startCharacter, endCharacter]` (single-line)
     * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
     *
     * The end line of a three-element range is inferred to equal the start line.
     *
     * Historical note: the original draft of this schema had a `Range` message
     * type with `start` and `end` fields of type `Position`, mirroring LSP.
     * Benchmarks revealed that this encoding was inefficient and that we could
     * reduce the total payload size of an index by 50% by using `repeated int32`
     * instead. However, the lack of type safety led to the introduction of
     * `single_line_range` and `multi_line_range` as typed alternatives; the
     * typed encoding's per-index size overhead is small (single-digit percent)
     * because ranges are only a fraction of a typical index payload.
     * ```
     *
     * `repeated int32 range = 1 [json_name = "range", deprecated = true];`
     */
    @kotlin.Deprecated(message = "Field range is deprecated")  public val range: com.google.protobuf.kotlin.DslList<kotlin.Int, RangeProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.rangeList
      )
    /**
     * ```
     * Deprecated: Use `single_line_range` or `multi_line_range` instead.
     *
     * Half-open [start, end) range. Must be exactly three or four elements:
     * - Three elements: `[startLine, startCharacter, endCharacter]` (single-line)
     * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
     *
     * The end line of a three-element range is inferred to equal the start line.
     *
     * Historical note: the original draft of this schema had a `Range` message
     * type with `start` and `end` fields of type `Position`, mirroring LSP.
     * Benchmarks revealed that this encoding was inefficient and that we could
     * reduce the total payload size of an index by 50% by using `repeated int32`
     * instead. However, the lack of type safety led to the introduction of
     * `single_line_range` and `multi_line_range` as typed alternatives; the
     * typed encoding's per-index size overhead is small (single-digit percent)
     * because ranges are only a fraction of a typical index payload.
     * ```
     *
     * `repeated int32 range = 1 [json_name = "range", deprecated = true];`
     * @param value The range to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addRange")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, RangeProxy>.add(value: kotlin.Int) {
      _builder.addRange(value)
    }/**
     * ```
     * Deprecated: Use `single_line_range` or `multi_line_range` instead.
     *
     * Half-open [start, end) range. Must be exactly three or four elements:
     * - Three elements: `[startLine, startCharacter, endCharacter]` (single-line)
     * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
     *
     * The end line of a three-element range is inferred to equal the start line.
     *
     * Historical note: the original draft of this schema had a `Range` message
     * type with `start` and `end` fields of type `Position`, mirroring LSP.
     * Benchmarks revealed that this encoding was inefficient and that we could
     * reduce the total payload size of an index by 50% by using `repeated int32`
     * instead. However, the lack of type safety led to the introduction of
     * `single_line_range` and `multi_line_range` as typed alternatives; the
     * typed encoding's per-index size overhead is small (single-digit percent)
     * because ranges are only a fraction of a typical index payload.
     * ```
     *
     * `repeated int32 range = 1 [json_name = "range", deprecated = true];`
     * @param value The range to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, RangeProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * ```
     * Deprecated: Use `single_line_range` or `multi_line_range` instead.
     *
     * Half-open [start, end) range. Must be exactly three or four elements:
     * - Three elements: `[startLine, startCharacter, endCharacter]` (single-line)
     * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
     *
     * The end line of a three-element range is inferred to equal the start line.
     *
     * Historical note: the original draft of this schema had a `Range` message
     * type with `start` and `end` fields of type `Position`, mirroring LSP.
     * Benchmarks revealed that this encoding was inefficient and that we could
     * reduce the total payload size of an index by 50% by using `repeated int32`
     * instead. However, the lack of type safety led to the introduction of
     * `single_line_range` and `multi_line_range` as typed alternatives; the
     * typed encoding's per-index size overhead is small (single-digit percent)
     * because ranges are only a fraction of a typical index payload.
     * ```
     *
     * `repeated int32 range = 1 [json_name = "range", deprecated = true];`
     * @param values The range to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllRange")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, RangeProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllRange(values)
    }/**
     * ```
     * Deprecated: Use `single_line_range` or `multi_line_range` instead.
     *
     * Half-open [start, end) range. Must be exactly three or four elements:
     * - Three elements: `[startLine, startCharacter, endCharacter]` (single-line)
     * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
     *
     * The end line of a three-element range is inferred to equal the start line.
     *
     * Historical note: the original draft of this schema had a `Range` message
     * type with `start` and `end` fields of type `Position`, mirroring LSP.
     * Benchmarks revealed that this encoding was inefficient and that we could
     * reduce the total payload size of an index by 50% by using `repeated int32`
     * instead. However, the lack of type safety led to the introduction of
     * `single_line_range` and `multi_line_range` as typed alternatives; the
     * typed encoding's per-index size overhead is small (single-digit percent)
     * because ranges are only a fraction of a typical index payload.
     * ```
     *
     * `repeated int32 range = 1 [json_name = "range", deprecated = true];`
     * @param values The range to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, RangeProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * ```
     * Deprecated: Use `single_line_range` or `multi_line_range` instead.
     *
     * Half-open [start, end) range. Must be exactly three or four elements:
     * - Three elements: `[startLine, startCharacter, endCharacter]` (single-line)
     * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
     *
     * The end line of a three-element range is inferred to equal the start line.
     *
     * Historical note: the original draft of this schema had a `Range` message
     * type with `start` and `end` fields of type `Position`, mirroring LSP.
     * Benchmarks revealed that this encoding was inefficient and that we could
     * reduce the total payload size of an index by 50% by using `repeated int32`
     * instead. However, the lack of type safety led to the introduction of
     * `single_line_range` and `multi_line_range` as typed alternatives; the
     * typed encoding's per-index size overhead is small (single-digit percent)
     * because ranges are only a fraction of a typical index payload.
     * ```
     *
     * `repeated int32 range = 1 [json_name = "range", deprecated = true];`
     * @param index The index to set the value at.
     * @param value The range to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setRange")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, RangeProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setRange(index, value)
    }/**
     * ```
     * Deprecated: Use `single_line_range` or `multi_line_range` instead.
     *
     * Half-open [start, end) range. Must be exactly three or four elements:
     * - Three elements: `[startLine, startCharacter, endCharacter]` (single-line)
     * - Four elements: `[startLine, startCharacter, endLine, endCharacter]`
     *
     * The end line of a three-element range is inferred to equal the start line.
     *
     * Historical note: the original draft of this schema had a `Range` message
     * type with `start` and `end` fields of type `Position`, mirroring LSP.
     * Benchmarks revealed that this encoding was inefficient and that we could
     * reduce the total payload size of an index by 50% by using `repeated int32`
     * instead. However, the lack of type safety led to the introduction of
     * `single_line_range` and `multi_line_range` as typed alternatives; the
     * typed encoding's per-index size overhead is small (single-digit percent)
     * because ranges are only a fraction of a typical index payload.
     * ```
     *
     * `repeated int32 range = 1 [json_name = "range", deprecated = true];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearRange")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, RangeProxy>.clear() {
      _builder.clearRange()
    }
    /**
     * ```
     * Range spanning a single line.
     * ```
     *
     * `.scip.SingleLineRange single_line_range = 8 [json_name = "singleLineRange"];`
     */
    public var singleLineRange: org.scip_code.scip.SingleLineRange
      @kotlin.jvm.JvmName("getSingleLineRange")
        get() = _builder.singleLineRange
      @kotlin.jvm.JvmName("setSingleLineRange")
        set(value) {
        _builder.singleLineRange = value
      }
    /**
     * ```
     * Range spanning a single line.
     * ```
     *
     * `.scip.SingleLineRange single_line_range = 8 [json_name = "singleLineRange"];`
     */
    public fun clearSingleLineRange() {
      _builder.clearSingleLineRange()
    }
    /**
     * ```
     * Range spanning a single line.
     * ```
     *
     * `.scip.SingleLineRange single_line_range = 8 [json_name = "singleLineRange"];`
     * @return Whether the singleLineRange field is set.
     */
    public fun hasSingleLineRange(): kotlin.Boolean {
      return _builder.hasSingleLineRange()
    }

    /**
     * ```
     * Range spanning multiple lines.
     * ```
     *
     * `.scip.MultiLineRange multi_line_range = 9 [json_name = "multiLineRange"];`
     */
    public var multiLineRange: org.scip_code.scip.MultiLineRange
      @kotlin.jvm.JvmName("getMultiLineRange")
        get() = _builder.multiLineRange
      @kotlin.jvm.JvmName("setMultiLineRange")
        set(value) {
        _builder.multiLineRange = value
      }
    /**
     * ```
     * Range spanning multiple lines.
     * ```
     *
     * `.scip.MultiLineRange multi_line_range = 9 [json_name = "multiLineRange"];`
     */
    public fun clearMultiLineRange() {
      _builder.clearMultiLineRange()
    }
    /**
     * ```
     * Range spanning multiple lines.
     * ```
     *
     * `.scip.MultiLineRange multi_line_range = 9 [json_name = "multiLineRange"];`
     * @return Whether the multiLineRange field is set.
     */
    public fun hasMultiLineRange(): kotlin.Boolean {
      return _builder.hasMultiLineRange()
    }

    /**
     * ```
     * (optional) The symbol that appears at this position. See
     * `SymbolInformation.symbol` for how to format symbols as strings.
     * ```
     *
     * `string symbol = 2 [json_name = "symbol"];`
     */
    public var symbol: kotlin.String
      @kotlin.jvm.JvmName("getSymbol")
        get() = _builder.symbol
      @kotlin.jvm.JvmName("setSymbol")
        set(value) {
        _builder.symbol = value
      }
    /**
     * ```
     * (optional) The symbol that appears at this position. See
     * `SymbolInformation.symbol` for how to format symbols as strings.
     * ```
     *
     * `string symbol = 2 [json_name = "symbol"];`
     */
    public fun clearSymbol() {
      _builder.clearSymbol()
    }

    /**
     * ```
     * (optional) Bitset containing `SymbolRole`s in this occurrence.
     * See `SymbolRole`'s documentation for how to read and write this field.
     * ```
     *
     * `int32 symbol_roles = 3 [json_name = "symbolRoles"];`
     */
    public var symbolRoles: kotlin.Int
      @kotlin.jvm.JvmName("getSymbolRoles")
        get() = _builder.symbolRoles
      @kotlin.jvm.JvmName("setSymbolRoles")
        set(value) {
        _builder.symbolRoles = value
      }
    /**
     * ```
     * (optional) Bitset containing `SymbolRole`s in this occurrence.
     * See `SymbolRole`'s documentation for how to read and write this field.
     * ```
     *
     * `int32 symbol_roles = 3 [json_name = "symbolRoles"];`
     */
    public fun clearSymbolRoles() {
      _builder.clearSymbolRoles()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OverrideDocumentationProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * (optional) CommonMark-formatted documentation for this specific range. If
     * empty, the `Symbol.documentation` field is used instead. One example
     * where this field might be useful is when the symbol represents a generic
     * function (with abstract type parameters such as `List<T>`) and at this
     * occurrence we know the exact values (such as `List<String>`).
     *
     * This field can also be used for dynamically or gradually typed languages,
     * which commonly allow for type-changing assignment.
     * ```
     *
     * `repeated string override_documentation = 4 [json_name = "overrideDocumentation"];`
     * @return A list containing the overrideDocumentation.
     */
    public val overrideDocumentation: com.google.protobuf.kotlin.DslList<kotlin.String, OverrideDocumentationProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.overrideDocumentationList
      )
    /**
     * ```
     * (optional) CommonMark-formatted documentation for this specific range. If
     * empty, the `Symbol.documentation` field is used instead. One example
     * where this field might be useful is when the symbol represents a generic
     * function (with abstract type parameters such as `List<T>`) and at this
     * occurrence we know the exact values (such as `List<String>`).
     *
     * This field can also be used for dynamically or gradually typed languages,
     * which commonly allow for type-changing assignment.
     * ```
     *
     * `repeated string override_documentation = 4 [json_name = "overrideDocumentation"];`
     * @param value The overrideDocumentation to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addOverrideDocumentation")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OverrideDocumentationProxy>.add(value: kotlin.String) {
      _builder.addOverrideDocumentation(value)
    }
    /**
     * ```
     * (optional) CommonMark-formatted documentation for this specific range. If
     * empty, the `Symbol.documentation` field is used instead. One example
     * where this field might be useful is when the symbol represents a generic
     * function (with abstract type parameters such as `List<T>`) and at this
     * occurrence we know the exact values (such as `List<String>`).
     *
     * This field can also be used for dynamically or gradually typed languages,
     * which commonly allow for type-changing assignment.
     * ```
     *
     * `repeated string override_documentation = 4 [json_name = "overrideDocumentation"];`
     * @param value The overrideDocumentation to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignOverrideDocumentation")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OverrideDocumentationProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * (optional) CommonMark-formatted documentation for this specific range. If
     * empty, the `Symbol.documentation` field is used instead. One example
     * where this field might be useful is when the symbol represents a generic
     * function (with abstract type parameters such as `List<T>`) and at this
     * occurrence we know the exact values (such as `List<String>`).
     *
     * This field can also be used for dynamically or gradually typed languages,
     * which commonly allow for type-changing assignment.
     * ```
     *
     * `repeated string override_documentation = 4 [json_name = "overrideDocumentation"];`
     * @param values The overrideDocumentation to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllOverrideDocumentation")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OverrideDocumentationProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllOverrideDocumentation(values)
    }
    /**
     * ```
     * (optional) CommonMark-formatted documentation for this specific range. If
     * empty, the `Symbol.documentation` field is used instead. One example
     * where this field might be useful is when the symbol represents a generic
     * function (with abstract type parameters such as `List<T>`) and at this
     * occurrence we know the exact values (such as `List<String>`).
     *
     * This field can also be used for dynamically or gradually typed languages,
     * which commonly allow for type-changing assignment.
     * ```
     *
     * `repeated string override_documentation = 4 [json_name = "overrideDocumentation"];`
     * @param values The overrideDocumentation to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllOverrideDocumentation")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OverrideDocumentationProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * (optional) CommonMark-formatted documentation for this specific range. If
     * empty, the `Symbol.documentation` field is used instead. One example
     * where this field might be useful is when the symbol represents a generic
     * function (with abstract type parameters such as `List<T>`) and at this
     * occurrence we know the exact values (such as `List<String>`).
     *
     * This field can also be used for dynamically or gradually typed languages,
     * which commonly allow for type-changing assignment.
     * ```
     *
     * `repeated string override_documentation = 4 [json_name = "overrideDocumentation"];`
     * @param index The index to set the value at.
     * @param value The overrideDocumentation to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setOverrideDocumentation")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OverrideDocumentationProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setOverrideDocumentation(index, value)
    }/**
     * ```
     * (optional) CommonMark-formatted documentation for this specific range. If
     * empty, the `Symbol.documentation` field is used instead. One example
     * where this field might be useful is when the symbol represents a generic
     * function (with abstract type parameters such as `List<T>`) and at this
     * occurrence we know the exact values (such as `List<String>`).
     *
     * This field can also be used for dynamically or gradually typed languages,
     * which commonly allow for type-changing assignment.
     * ```
     *
     * `repeated string override_documentation = 4 [json_name = "overrideDocumentation"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setOverrideDocumentation")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OverrideDocumentationProxy>.clear() {
      _builder.clearOverrideDocumentation()
    }
    /**
     * ```
     * (optional) What syntax highlighting class should be used for this range?
     * ```
     *
     * `.scip.SyntaxKind syntax_kind = 5 [json_name = "syntaxKind"];`
     */
    public var syntaxKind: org.scip_code.scip.SyntaxKind
      @kotlin.jvm.JvmName("getSyntaxKind")
        get() = _builder.syntaxKind
      @kotlin.jvm.JvmName("setSyntaxKind")
        set(value) {
        _builder.syntaxKind = value
      }
    public var syntaxKindValue: kotlin.Int
      @kotlin.jvm.JvmName("getSyntaxKindValue")
        get() = _builder.syntaxKindValue
      @kotlin.jvm.JvmName("setSyntaxKindValue")
        set(value) {
        _builder.syntaxKindValue = value
      }
    /**
     * ```
     * (optional) What syntax highlighting class should be used for this range?
     * ```
     *
     * `.scip.SyntaxKind syntax_kind = 5 [json_name = "syntaxKind"];`
     */
    public fun clearSyntaxKind() {
      _builder.clearSyntaxKind()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DiagnosticsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * (optional) Diagnostics that have been reported for this specific range.
     * ```
     *
     * `repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];`
     */
     public val diagnostics: com.google.protobuf.kotlin.DslList<org.scip_code.scip.Diagnostic, DiagnosticsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.diagnosticsList
      )
    /**
     * ```
     * (optional) Diagnostics that have been reported for this specific range.
     * ```
     *
     * `repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];`
     * @param value The diagnostics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addDiagnostics")
    public fun com.google.protobuf.kotlin.DslList<org.scip_code.scip.Diagnostic, DiagnosticsProxy>.add(value: org.scip_code.scip.Diagnostic) {
      _builder.addDiagnostics(value)
    }
    /**
     * ```
     * (optional) Diagnostics that have been reported for this specific range.
     * ```
     *
     * `repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];`
     * @param value The diagnostics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignDiagnostics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<org.scip_code.scip.Diagnostic, DiagnosticsProxy>.plusAssign(value: org.scip_code.scip.Diagnostic) {
      add(value)
    }
    /**
     * ```
     * (optional) Diagnostics that have been reported for this specific range.
     * ```
     *
     * `repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];`
     * @param values The diagnostics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllDiagnostics")
    public fun com.google.protobuf.kotlin.DslList<org.scip_code.scip.Diagnostic, DiagnosticsProxy>.addAll(values: kotlin.collections.Iterable<org.scip_code.scip.Diagnostic>) {
      _builder.addAllDiagnostics(values)
    }
    /**
     * ```
     * (optional) Diagnostics that have been reported for this specific range.
     * ```
     *
     * `repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];`
     * @param values The diagnostics to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllDiagnostics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<org.scip_code.scip.Diagnostic, DiagnosticsProxy>.plusAssign(values: kotlin.collections.Iterable<org.scip_code.scip.Diagnostic>) {
      addAll(values)
    }
    /**
     * ```
     * (optional) Diagnostics that have been reported for this specific range.
     * ```
     *
     * `repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];`
     * @param index The index to set the value at.
     * @param value The diagnostics to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDiagnostics")
    public operator fun com.google.protobuf.kotlin.DslList<org.scip_code.scip.Diagnostic, DiagnosticsProxy>.set(index: kotlin.Int, value: org.scip_code.scip.Diagnostic) {
      _builder.setDiagnostics(index, value)
    }
    /**
     * ```
     * (optional) Diagnostics that have been reported for this specific range.
     * ```
     *
     * `repeated .scip.Diagnostic diagnostics = 6 [json_name = "diagnostics"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearDiagnostics")
    public fun com.google.protobuf.kotlin.DslList<org.scip_code.scip.Diagnostic, DiagnosticsProxy>.clear() {
      _builder.clearDiagnostics()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EnclosingRangeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Deprecated: Use `typed_enclosing_range` instead.
     *
     * Uses the same `repeated int32` encoding as the deprecated `range` field.
     * ```
     *
     * `repeated int32 enclosing_range = 7 [json_name = "enclosingRange", deprecated = true];`
     */
    @kotlin.Deprecated(message = "Field enclosingRange is deprecated")  public val enclosingRange: com.google.protobuf.kotlin.DslList<kotlin.Int, EnclosingRangeProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.enclosingRangeList
      )
    /**
     * ```
     * Deprecated: Use `typed_enclosing_range` instead.
     *
     * Uses the same `repeated int32` encoding as the deprecated `range` field.
     * ```
     *
     * `repeated int32 enclosing_range = 7 [json_name = "enclosingRange", deprecated = true];`
     * @param value The enclosingRange to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addEnclosingRange")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, EnclosingRangeProxy>.add(value: kotlin.Int) {
      _builder.addEnclosingRange(value)
    }/**
     * ```
     * Deprecated: Use `typed_enclosing_range` instead.
     *
     * Uses the same `repeated int32` encoding as the deprecated `range` field.
     * ```
     *
     * `repeated int32 enclosing_range = 7 [json_name = "enclosingRange", deprecated = true];`
     * @param value The enclosingRange to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignEnclosingRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, EnclosingRangeProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * ```
     * Deprecated: Use `typed_enclosing_range` instead.
     *
     * Uses the same `repeated int32` encoding as the deprecated `range` field.
     * ```
     *
     * `repeated int32 enclosing_range = 7 [json_name = "enclosingRange", deprecated = true];`
     * @param values The enclosingRange to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllEnclosingRange")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, EnclosingRangeProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllEnclosingRange(values)
    }/**
     * ```
     * Deprecated: Use `typed_enclosing_range` instead.
     *
     * Uses the same `repeated int32` encoding as the deprecated `range` field.
     * ```
     *
     * `repeated int32 enclosing_range = 7 [json_name = "enclosingRange", deprecated = true];`
     * @param values The enclosingRange to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllEnclosingRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, EnclosingRangeProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * ```
     * Deprecated: Use `typed_enclosing_range` instead.
     *
     * Uses the same `repeated int32` encoding as the deprecated `range` field.
     * ```
     *
     * `repeated int32 enclosing_range = 7 [json_name = "enclosingRange", deprecated = true];`
     * @param index The index to set the value at.
     * @param value The enclosingRange to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEnclosingRange")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, EnclosingRangeProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setEnclosingRange(index, value)
    }/**
     * ```
     * Deprecated: Use `typed_enclosing_range` instead.
     *
     * Uses the same `repeated int32` encoding as the deprecated `range` field.
     * ```
     *
     * `repeated int32 enclosing_range = 7 [json_name = "enclosingRange", deprecated = true];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearEnclosingRange")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, EnclosingRangeProxy>.clear() {
      _builder.clearEnclosingRange()
    }
    /**
     * ```
     * Enclosing range spanning a single line.
     * ```
     *
     * `.scip.SingleLineRange single_line_enclosing_range = 10 [json_name = "singleLineEnclosingRange"];`
     */
    public var singleLineEnclosingRange: org.scip_code.scip.SingleLineRange
      @kotlin.jvm.JvmName("getSingleLineEnclosingRange")
        get() = _builder.singleLineEnclosingRange
      @kotlin.jvm.JvmName("setSingleLineEnclosingRange")
        set(value) {
        _builder.singleLineEnclosingRange = value
      }
    /**
     * ```
     * Enclosing range spanning a single line.
     * ```
     *
     * `.scip.SingleLineRange single_line_enclosing_range = 10 [json_name = "singleLineEnclosingRange"];`
     */
    public fun clearSingleLineEnclosingRange() {
      _builder.clearSingleLineEnclosingRange()
    }
    /**
     * ```
     * Enclosing range spanning a single line.
     * ```
     *
     * `.scip.SingleLineRange single_line_enclosing_range = 10 [json_name = "singleLineEnclosingRange"];`
     * @return Whether the singleLineEnclosingRange field is set.
     */
    public fun hasSingleLineEnclosingRange(): kotlin.Boolean {
      return _builder.hasSingleLineEnclosingRange()
    }

    /**
     * ```
     * Enclosing range spanning multiple lines.
     * ```
     *
     * `.scip.MultiLineRange multi_line_enclosing_range = 11 [json_name = "multiLineEnclosingRange"];`
     */
    public var multiLineEnclosingRange: org.scip_code.scip.MultiLineRange
      @kotlin.jvm.JvmName("getMultiLineEnclosingRange")
        get() = _builder.multiLineEnclosingRange
      @kotlin.jvm.JvmName("setMultiLineEnclosingRange")
        set(value) {
        _builder.multiLineEnclosingRange = value
      }
    /**
     * ```
     * Enclosing range spanning multiple lines.
     * ```
     *
     * `.scip.MultiLineRange multi_line_enclosing_range = 11 [json_name = "multiLineEnclosingRange"];`
     */
    public fun clearMultiLineEnclosingRange() {
      _builder.clearMultiLineEnclosingRange()
    }
    /**
     * ```
     * Enclosing range spanning multiple lines.
     * ```
     *
     * `.scip.MultiLineRange multi_line_enclosing_range = 11 [json_name = "multiLineEnclosingRange"];`
     * @return Whether the multiLineEnclosingRange field is set.
     */
    public fun hasMultiLineEnclosingRange(): kotlin.Boolean {
      return _builder.hasMultiLineEnclosingRange()
    }
    public val typedRangeCase: org.scip_code.scip.Occurrence.TypedRangeCase
    @kotlin.jvm.JvmName("getTypedRangeCase")
      get() = _builder.getTypedRangeCase()

    public fun clearTypedRange() {
      _builder.clearTypedRange()
    }
    public val typedEnclosingRangeCase: org.scip_code.scip.Occurrence.TypedEnclosingRangeCase
    @kotlin.jvm.JvmName("getTypedEnclosingRangeCase")
      get() = _builder.getTypedEnclosingRangeCase()

    public fun clearTypedEnclosingRange() {
      _builder.clearTypedEnclosingRange()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.scip_code.scip.Occurrence.copy(block: `org.scip_code.scip`.OccurrenceKt.Dsl.() -> kotlin.Unit): org.scip_code.scip.Occurrence =
  `org.scip_code.scip`.OccurrenceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val org.scip_code.scip.OccurrenceOrBuilder.singleLineRangeOrNull: org.scip_code.scip.SingleLineRange?
  get() = if (hasSingleLineRange()) getSingleLineRange() else null

public val org.scip_code.scip.OccurrenceOrBuilder.multiLineRangeOrNull: org.scip_code.scip.MultiLineRange?
  get() = if (hasMultiLineRange()) getMultiLineRange() else null

public val org.scip_code.scip.OccurrenceOrBuilder.singleLineEnclosingRangeOrNull: org.scip_code.scip.SingleLineRange?
  get() = if (hasSingleLineEnclosingRange()) getSingleLineEnclosingRange() else null

public val org.scip_code.scip.OccurrenceOrBuilder.multiLineEnclosingRangeOrNull: org.scip_code.scip.MultiLineRange?
  get() = if (hasMultiLineEnclosingRange()) getMultiLineEnclosingRange() else null

