// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package scip;

@kotlin.jvm.JvmName("-initializedescriptor")
public inline fun descriptor(block: scip.DescriptorKt.Dsl.() -> kotlin.Unit): scip.Scip.Descriptor =
  scip.DescriptorKt.Dsl._create(scip.Scip.Descriptor.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `scip.Descriptor`
 */
public object DescriptorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: scip.Scip.Descriptor.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: scip.Scip.Descriptor.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): scip.Scip.Descriptor = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string disambiguator = 2 [json_name = "disambiguator"];`
     */
    public var disambiguator: kotlin.String
      @kotlin.jvm.JvmName("getDisambiguator")
        get() = _builder.disambiguator
      @kotlin.jvm.JvmName("setDisambiguator")
        set(value) {
        _builder.disambiguator = value
      }
    /**
     * `string disambiguator = 2 [json_name = "disambiguator"];`
     */
    public fun clearDisambiguator() {
      _builder.clearDisambiguator()
    }

    /**
     * ```
     * NOTE: If you add new fields here, make sure to update the prepareSlot()
     * function responsible for parsing symbols.
     * ```
     *
     * `.scip.Descriptor.Suffix suffix = 3 [json_name = "suffix"];`
     */
    public var suffix: scip.Scip.Descriptor.Suffix
      @kotlin.jvm.JvmName("getSuffix")
        get() = _builder.suffix
      @kotlin.jvm.JvmName("setSuffix")
        set(value) {
        _builder.suffix = value
      }
    public var suffixValue: kotlin.Int
      @kotlin.jvm.JvmName("getSuffixValue")
        get() = _builder.suffixValue
      @kotlin.jvm.JvmName("setSuffixValue")
        set(value) {
        _builder.suffixValue = value
      }
    /**
     * ```
     * NOTE: If you add new fields here, make sure to update the prepareSlot()
     * function responsible for parsing symbols.
     * ```
     *
     * `.scip.Descriptor.Suffix suffix = 3 [json_name = "suffix"];`
     */
    public fun clearSuffix() {
      _builder.clearSuffix()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun scip.Scip.Descriptor.copy(block: `scip`.DescriptorKt.Dsl.() -> kotlin.Unit): scip.Scip.Descriptor =
  `scip`.DescriptorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

