// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package scip;

@kotlin.jvm.JvmName("-initializediagnostic")
public inline fun diagnostic(block: scip.DiagnosticKt.Dsl.() -> kotlin.Unit): scip.Scip.Diagnostic =
  scip.DiagnosticKt.Dsl._create(scip.Scip.Diagnostic.newBuilder()).apply { block() }._build()
/**
 * ```
 * Represents a diagnostic, such as a compiler error or warning, which should be
 * reported for a document.
 * ```
 *
 * Protobuf type `scip.Diagnostic`
 */
public object DiagnosticKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: scip.Scip.Diagnostic.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: scip.Scip.Diagnostic.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): scip.Scip.Diagnostic = _builder.build()

    /**
     * ```
     * Should this diagnostic be reported as an error, warning, info, or hint?
     * ```
     *
     * `.scip.Severity severity = 1 [json_name = "severity"];`
     */
    public var severity: scip.Scip.Severity
      @kotlin.jvm.JvmName("getSeverity")
        get() = _builder.severity
      @kotlin.jvm.JvmName("setSeverity")
        set(value) {
        _builder.severity = value
      }
    public var severityValue: kotlin.Int
      @kotlin.jvm.JvmName("getSeverityValue")
        get() = _builder.severityValue
      @kotlin.jvm.JvmName("setSeverityValue")
        set(value) {
        _builder.severityValue = value
      }
    /**
     * ```
     * Should this diagnostic be reported as an error, warning, info, or hint?
     * ```
     *
     * `.scip.Severity severity = 1 [json_name = "severity"];`
     */
    public fun clearSeverity() {
      _builder.clearSeverity()
    }

    /**
     * ```
     * (optional) Code of this diagnostic, which might appear in the user interface.
     * ```
     *
     * `string code = 2 [json_name = "code"];`
     */
    public var code: kotlin.String
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * ```
     * (optional) Code of this diagnostic, which might appear in the user interface.
     * ```
     *
     * `string code = 2 [json_name = "code"];`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * ```
     * Message of this diagnostic.
     * ```
     *
     * `string message = 3 [json_name = "message"];`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * ```
     * Message of this diagnostic.
     * ```
     *
     * `string message = 3 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * (optional) Human-readable string describing the source of this diagnostic, e.g.
     * 'typescript' or 'super lint'.
     * ```
     *
     * `string source = 4 [json_name = "source"];`
     */
    public var source: kotlin.String
      @kotlin.jvm.JvmName("getSource")
        get() = _builder.source
      @kotlin.jvm.JvmName("setSource")
        set(value) {
        _builder.source = value
      }
    /**
     * ```
     * (optional) Human-readable string describing the source of this diagnostic, e.g.
     * 'typescript' or 'super lint'.
     * ```
     *
     * `string source = 4 [json_name = "source"];`
     */
    public fun clearSource() {
      _builder.clearSource()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .scip.DiagnosticTag tags = 5 [json_name = "tags"];`
     */
     public val tags: com.google.protobuf.kotlin.DslList<scip.Scip.DiagnosticTag, TagsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.tagsList
      )
    /**
     * `repeated .scip.DiagnosticTag tags = 5 [json_name = "tags"];`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addTags")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.DiagnosticTag, TagsProxy>.add(value: scip.Scip.DiagnosticTag) {
      _builder.addTags(value)
    }/**
     * `repeated .scip.DiagnosticTag tags = 5 [json_name = "tags"];`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<scip.Scip.DiagnosticTag, TagsProxy>.plusAssign(value: scip.Scip.DiagnosticTag) {
      add(value)
    }/**
     * `repeated .scip.DiagnosticTag tags = 5 [json_name = "tags"];`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllTags")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.DiagnosticTag, TagsProxy>.addAll(values: kotlin.collections.Iterable<scip.Scip.DiagnosticTag>) {
      _builder.addAllTags(values)
    }/**
     * `repeated .scip.DiagnosticTag tags = 5 [json_name = "tags"];`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<scip.Scip.DiagnosticTag, TagsProxy>.plusAssign(values: kotlin.collections.Iterable<scip.Scip.DiagnosticTag>) {
      addAll(values)
    }/**
     * `repeated .scip.DiagnosticTag tags = 5 [json_name = "tags"];`
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setTags")
    public operator fun com.google.protobuf.kotlin.DslList<scip.Scip.DiagnosticTag, TagsProxy>.set(index: kotlin.Int, value: scip.Scip.DiagnosticTag) {
      _builder.setTags(index, value)
    }/**
     * `repeated .scip.DiagnosticTag tags = 5 [json_name = "tags"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearTags")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.DiagnosticTag, TagsProxy>.clear() {
      _builder.clearTags()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun scip.Scip.Diagnostic.copy(block: `scip`.DiagnosticKt.Dsl.() -> kotlin.Unit): scip.Scip.Diagnostic =
  `scip`.DiagnosticKt.Dsl._create(this.toBuilder()).apply { block() }._build()

