// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scip.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package scip;

@kotlin.jvm.JvmName("-initializedocument")
public inline fun document(block: scip.DocumentKt.Dsl.() -> kotlin.Unit): scip.Scip.Document =
  scip.DocumentKt.Dsl._create(scip.Scip.Document.newBuilder()).apply { block() }._build()
/**
 * ```
 * Document defines the metadata about a source file on disk.
 * ```
 *
 * Protobuf type `scip.Document`
 */
public object DocumentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: scip.Scip.Document.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: scip.Scip.Document.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): scip.Scip.Document = _builder.build()

    /**
     * ```
     * The string ID for the programming language this file is written in.
     * The `Language` enum contains the names of most common programming languages.
     * This field is typed as a string to permit any programming language, including
     * ones that are not specified by the `Language` enum.
     * ```
     *
     * `string language = 4 [json_name = "language"];`
     */
    public var language: kotlin.String
      @kotlin.jvm.JvmName("getLanguage")
        get() = _builder.language
      @kotlin.jvm.JvmName("setLanguage")
        set(value) {
        _builder.language = value
      }
    /**
     * ```
     * The string ID for the programming language this file is written in.
     * The `Language` enum contains the names of most common programming languages.
     * This field is typed as a string to permit any programming language, including
     * ones that are not specified by the `Language` enum.
     * ```
     *
     * `string language = 4 [json_name = "language"];`
     */
    public fun clearLanguage() {
      _builder.clearLanguage()
    }

    /**
     * ```
     * (Required) Unique path to the text document.
     *
     * 1. The path must be relative to the directory supplied in the associated
     * `Metadata.project_root`.
     * 2. The path must not begin with a leading '/'.
     * 3. The path must point to a regular file, not a symbolic link.
     * 4. The path must use '/' as the separator, including on Windows.
     * 5. The path must be canonical; it cannot include empty components ('//'),
     * or '.' or '..'.
     * ```
     *
     * `string relative_path = 1 [json_name = "relativePath"];`
     */
    public var relativePath: kotlin.String
      @kotlin.jvm.JvmName("getRelativePath")
        get() = _builder.relativePath
      @kotlin.jvm.JvmName("setRelativePath")
        set(value) {
        _builder.relativePath = value
      }
    /**
     * ```
     * (Required) Unique path to the text document.
     *
     * 1. The path must be relative to the directory supplied in the associated
     * `Metadata.project_root`.
     * 2. The path must not begin with a leading '/'.
     * 3. The path must point to a regular file, not a symbolic link.
     * 4. The path must use '/' as the separator, including on Windows.
     * 5. The path must be canonical; it cannot include empty components ('//'),
     * or '.' or '..'.
     * ```
     *
     * `string relative_path = 1 [json_name = "relativePath"];`
     */
    public fun clearRelativePath() {
      _builder.clearRelativePath()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OccurrencesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Occurrences that appear in this file.
     * ```
     *
     * `repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];`
     */
     public val occurrences: com.google.protobuf.kotlin.DslList<scip.Scip.Occurrence, OccurrencesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.occurrencesList
      )
    /**
     * ```
     * Occurrences that appear in this file.
     * ```
     *
     * `repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];`
     * @param value The occurrences to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addOccurrences")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.Occurrence, OccurrencesProxy>.add(value: scip.Scip.Occurrence) {
      _builder.addOccurrences(value)
    }
    /**
     * ```
     * Occurrences that appear in this file.
     * ```
     *
     * `repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];`
     * @param value The occurrences to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignOccurrences")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<scip.Scip.Occurrence, OccurrencesProxy>.plusAssign(value: scip.Scip.Occurrence) {
      add(value)
    }
    /**
     * ```
     * Occurrences that appear in this file.
     * ```
     *
     * `repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];`
     * @param values The occurrences to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllOccurrences")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.Occurrence, OccurrencesProxy>.addAll(values: kotlin.collections.Iterable<scip.Scip.Occurrence>) {
      _builder.addAllOccurrences(values)
    }
    /**
     * ```
     * Occurrences that appear in this file.
     * ```
     *
     * `repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];`
     * @param values The occurrences to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllOccurrences")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<scip.Scip.Occurrence, OccurrencesProxy>.plusAssign(values: kotlin.collections.Iterable<scip.Scip.Occurrence>) {
      addAll(values)
    }
    /**
     * ```
     * Occurrences that appear in this file.
     * ```
     *
     * `repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];`
     * @param index The index to set the value at.
     * @param value The occurrences to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setOccurrences")
    public operator fun com.google.protobuf.kotlin.DslList<scip.Scip.Occurrence, OccurrencesProxy>.set(index: kotlin.Int, value: scip.Scip.Occurrence) {
      _builder.setOccurrences(index, value)
    }
    /**
     * ```
     * Occurrences that appear in this file.
     * ```
     *
     * `repeated .scip.Occurrence occurrences = 2 [json_name = "occurrences"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearOccurrences")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.Occurrence, OccurrencesProxy>.clear() {
      _builder.clearOccurrences()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SymbolsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Symbols that are "defined" within this document.
     *
     * This should include symbols which technically do not have any definition,
     * but have a reference and are defined by some other symbol (see
     * Relationship.is_definition).
     * ```
     *
     * `repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];`
     */
     public val symbols: com.google.protobuf.kotlin.DslList<scip.Scip.SymbolInformation, SymbolsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.symbolsList
      )
    /**
     * ```
     * Symbols that are "defined" within this document.
     *
     * This should include symbols which technically do not have any definition,
     * but have a reference and are defined by some other symbol (see
     * Relationship.is_definition).
     * ```
     *
     * `repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];`
     * @param value The symbols to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSymbols")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.SymbolInformation, SymbolsProxy>.add(value: scip.Scip.SymbolInformation) {
      _builder.addSymbols(value)
    }
    /**
     * ```
     * Symbols that are "defined" within this document.
     *
     * This should include symbols which technically do not have any definition,
     * but have a reference and are defined by some other symbol (see
     * Relationship.is_definition).
     * ```
     *
     * `repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];`
     * @param value The symbols to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSymbols")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<scip.Scip.SymbolInformation, SymbolsProxy>.plusAssign(value: scip.Scip.SymbolInformation) {
      add(value)
    }
    /**
     * ```
     * Symbols that are "defined" within this document.
     *
     * This should include symbols which technically do not have any definition,
     * but have a reference and are defined by some other symbol (see
     * Relationship.is_definition).
     * ```
     *
     * `repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];`
     * @param values The symbols to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSymbols")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.SymbolInformation, SymbolsProxy>.addAll(values: kotlin.collections.Iterable<scip.Scip.SymbolInformation>) {
      _builder.addAllSymbols(values)
    }
    /**
     * ```
     * Symbols that are "defined" within this document.
     *
     * This should include symbols which technically do not have any definition,
     * but have a reference and are defined by some other symbol (see
     * Relationship.is_definition).
     * ```
     *
     * `repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];`
     * @param values The symbols to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSymbols")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<scip.Scip.SymbolInformation, SymbolsProxy>.plusAssign(values: kotlin.collections.Iterable<scip.Scip.SymbolInformation>) {
      addAll(values)
    }
    /**
     * ```
     * Symbols that are "defined" within this document.
     *
     * This should include symbols which technically do not have any definition,
     * but have a reference and are defined by some other symbol (see
     * Relationship.is_definition).
     * ```
     *
     * `repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];`
     * @param index The index to set the value at.
     * @param value The symbols to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSymbols")
    public operator fun com.google.protobuf.kotlin.DslList<scip.Scip.SymbolInformation, SymbolsProxy>.set(index: kotlin.Int, value: scip.Scip.SymbolInformation) {
      _builder.setSymbols(index, value)
    }
    /**
     * ```
     * Symbols that are "defined" within this document.
     *
     * This should include symbols which technically do not have any definition,
     * but have a reference and are defined by some other symbol (see
     * Relationship.is_definition).
     * ```
     *
     * `repeated .scip.SymbolInformation symbols = 3 [json_name = "symbols"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSymbols")
    public fun com.google.protobuf.kotlin.DslList<scip.Scip.SymbolInformation, SymbolsProxy>.clear() {
      _builder.clearSymbols()
    }

    /**
     * ```
     * (optional) Text contents of this document. Indexers are not expected to
     * include the text by default. It's preferable that clients read the text
     * contents from the file system by resolving the absolute path from joining
     * `Index.metadata.project_root` and `Document.relative_path`. This field
     * can be useful for testing or when working with virtual/in-memory documents.
     * ```
     *
     * `string text = 5 [json_name = "text"];`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * ```
     * (optional) Text contents of this document. Indexers are not expected to
     * include the text by default. It's preferable that clients read the text
     * contents from the file system by resolving the absolute path from joining
     * `Index.metadata.project_root` and `Document.relative_path`. This field
     * can be useful for testing or when working with virtual/in-memory documents.
     * ```
     *
     * `string text = 5 [json_name = "text"];`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * Specifies the encoding used for source ranges in this Document.
     *
     * Usually, this will match the type used to index the string type
     * in the indexer's implementation language in O(1) time.
     * - For an indexer implemented in JVM/.NET language or JavaScript/TypeScript,
     * use UTF16CodeUnitOffsetFromLineStart.
     * - For an indexer implemented in Python,
     * use UTF32CodeUnitOffsetFromLineStart.
     * - For an indexer implemented in Go, Rust or C++,
     * use UTF8ByteOffsetFromLineStart.
     * ```
     *
     * `.scip.PositionEncoding position_encoding = 6 [json_name = "positionEncoding"];`
     */
    public var positionEncoding: scip.Scip.PositionEncoding
      @kotlin.jvm.JvmName("getPositionEncoding")
        get() = _builder.positionEncoding
      @kotlin.jvm.JvmName("setPositionEncoding")
        set(value) {
        _builder.positionEncoding = value
      }
    public var positionEncodingValue: kotlin.Int
      @kotlin.jvm.JvmName("getPositionEncodingValue")
        get() = _builder.positionEncodingValue
      @kotlin.jvm.JvmName("setPositionEncodingValue")
        set(value) {
        _builder.positionEncodingValue = value
      }
    /**
     * ```
     * Specifies the encoding used for source ranges in this Document.
     *
     * Usually, this will match the type used to index the string type
     * in the indexer's implementation language in O(1) time.
     * - For an indexer implemented in JVM/.NET language or JavaScript/TypeScript,
     * use UTF16CodeUnitOffsetFromLineStart.
     * - For an indexer implemented in Python,
     * use UTF32CodeUnitOffsetFromLineStart.
     * - For an indexer implemented in Go, Rust or C++,
     * use UTF8ByteOffsetFromLineStart.
     * ```
     *
     * `.scip.PositionEncoding position_encoding = 6 [json_name = "positionEncoding"];`
     */
    public fun clearPositionEncoding() {
      _builder.clearPositionEncoding()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun scip.Scip.Document.copy(block: `scip`.DocumentKt.Dsl.() -> kotlin.Unit): scip.Scip.Document =
  `scip`.DocumentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

