/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name = 1,
  anon_sym_definition = 2,
  anon_sym_reference = 3,
  sym_forward_definition = 4,
  anon_sym_implements = 5,
  anon_sym_type_defines = 6,
  anon_sym_references = 7,
  anon_sym_relationships = 8,
  anon_sym_defined_by = 9,
  anon_sym_POUND = 10,
  aux_sym_comment_token1 = 11,
  anon_sym_POUNDdocstring_COLON = 12,
  anon_sym_local = 13,
  sym_source_file = 14,
  sym__statement = 15,
  sym_definition_statement = 16,
  sym_reference_statement = 17,
  sym__definition_relations = 18,
  sym_implements = 19,
  sym_type_defines = 20,
  sym_references = 21,
  sym_relationships_statement = 22,
  sym__all_relations = 23,
  sym_defined_by = 24,
  sym_comment = 25,
  sym_docstring = 26,
  sym_identifier = 27,
  sym_local_identifier = 28,
  sym_global_identifier = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_definition_statement_repeat1 = 31,
  aux_sym_relationships_statement_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_definition] = "definition",
  [anon_sym_reference] = "reference",
  [sym_forward_definition] = "forward_definition",
  [anon_sym_implements] = "implements",
  [anon_sym_type_defines] = "type_defines",
  [anon_sym_references] = "references",
  [anon_sym_relationships] = "relationships",
  [anon_sym_defined_by] = "defined_by",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_POUNDdocstring_COLON] = "# docstring:",
  [anon_sym_local] = "local",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_definition_statement] = "definition_statement",
  [sym_reference_statement] = "reference_statement",
  [sym__definition_relations] = "_definition_relations",
  [sym_implements] = "implements",
  [sym_type_defines] = "type_defines",
  [sym_references] = "references",
  [sym_relationships_statement] = "relationships_statement",
  [sym__all_relations] = "_all_relations",
  [sym_defined_by] = "defined_by",
  [sym_comment] = "comment",
  [sym_docstring] = "docstring",
  [sym_identifier] = "identifier",
  [sym_local_identifier] = "local_identifier",
  [sym_global_identifier] = "global_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_definition_statement_repeat1] = "definition_statement_repeat1",
  [aux_sym_relationships_statement_repeat1] = "relationships_statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_definition] = anon_sym_definition,
  [anon_sym_reference] = anon_sym_reference,
  [sym_forward_definition] = sym_forward_definition,
  [anon_sym_implements] = anon_sym_implements,
  [anon_sym_type_defines] = anon_sym_type_defines,
  [anon_sym_references] = anon_sym_references,
  [anon_sym_relationships] = anon_sym_relationships,
  [anon_sym_defined_by] = anon_sym_defined_by,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUNDdocstring_COLON] = anon_sym_POUNDdocstring_COLON,
  [anon_sym_local] = anon_sym_local,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_definition_statement] = sym_definition_statement,
  [sym_reference_statement] = sym_reference_statement,
  [sym__definition_relations] = sym__definition_relations,
  [sym_implements] = sym_implements,
  [sym_type_defines] = sym_type_defines,
  [sym_references] = sym_references,
  [sym_relationships_statement] = sym_relationships_statement,
  [sym__all_relations] = sym__all_relations,
  [sym_defined_by] = sym_defined_by,
  [sym_comment] = sym_comment,
  [sym_docstring] = sym_docstring,
  [sym_identifier] = sym_identifier,
  [sym_local_identifier] = sym_local_identifier,
  [sym_global_identifier] = sym_global_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_definition_statement_repeat1] = aux_sym_definition_statement_repeat1,
  [aux_sym_relationships_statement_repeat1] = aux_sym_relationships_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_definition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reference] = {
    .visible = true,
    .named = false,
  },
  [sym_forward_definition] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_implements] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type_defines] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_references] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_relationships] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defined_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUNDdocstring_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_definition_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_reference_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__definition_relations] = {
    .visible = false,
    .named = true,
  },
  [sym_implements] = {
    .visible = true,
    .named = true,
  },
  [sym_type_defines] = {
    .visible = true,
    .named = true,
  },
  [sym_references] = {
    .visible = true,
    .named = true,
  },
  [sym_relationships_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__all_relations] = {
    .visible = false,
    .named = true,
  },
  [sym_defined_by] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_docstring] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_local_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_global_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_definition_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_relationships_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_descriptors = 1,
  field_docstring = 2,
  field_global = 3,
  field_local = 4,
  field_name = 5,
  field_project_name = 6,
  field_relations = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_descriptors] = "descriptors",
  [field_docstring] = "docstring",
  [field_global] = "global",
  [field_local] = "local",
  [field_name] = "name",
  [field_project_name] = "project_name",
  [field_relations] = "relations",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_local, 0},
  [2] =
    {field_global, 0},
  [3] =
    {field_descriptors, 1},
    {field_project_name, 0},
  [5] =
    {field_name, 1},
    {field_relations, 2},
  [7] =
    {field_name, 2},
  [8] =
    {field_docstring, 0},
    {field_name, 2},
  [10] =
    {field_docstring, 0},
    {field_name, 2},
    {field_relations, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 12,
  [23] = 16,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 17,
  [29] = 14,
  [30] = 15,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 33,
  [39] = 39,
  [40] = 31,
  [41] = 32,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(80);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == 'd') ADVANCE(110);
      if (lookahead == 'i') ADVANCE(140);
      if (lookahead == 'r') ADVANCE(111);
      if (lookahead == 't') ADVANCE(165);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0) ADVANCE(166);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(101);
      END_STATE();
    case 2:
      if (lookahead == '_') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == '_') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(70);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(73);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(64);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(55);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(2);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'f') ADVANCE(17);
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 29:
      if (lookahead == 'f') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'f') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 33:
      if (lookahead == 'g') ADVANCE(1);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(57);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 44:
      if (lookahead == 'm') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(81);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(71);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 58:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 59:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 60:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(69);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(93);
      END_STATE();
    case 67:
      if (lookahead == 's') ADVANCE(87);
      END_STATE();
    case 68:
      if (lookahead == 's') ADVANCE(89);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 73:
      if (lookahead == 'y') ADVANCE(95);
      END_STATE();
    case 74:
      if (lookahead == 'y') ADVANCE(60);
      END_STATE();
    case 75:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(75);
      if (lookahead != 0) ADVANCE(166);
      END_STATE();
    case 76:
      if (eof) ADVANCE(80);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == 'd') ADVANCE(124);
      if (lookahead == 'i') ADVANCE(140);
      if (lookahead == 'r') ADVANCE(111);
      if (lookahead == 't') ADVANCE(165);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(76);
      if (lookahead != 0) ADVANCE(166);
      END_STATE();
    case 77:
      if (eof) ADVANCE(80);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == 'd') ADVANCE(124);
      if (lookahead == 'r') ADVANCE(125);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(77);
      if (lookahead != 0) ADVANCE(166);
      END_STATE();
    case 78:
      if (eof) ADVANCE(80);
      if (lookahead == '#') ADVANCE(97);
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(78);
      END_STATE();
    case 79:
      if (eof) ADVANCE(80);
      if (lookahead == '#') ADVANCE(97);
      if (lookahead == 'd') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 'r') ADVANCE(27);
      if (lookahead == 't') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_definition);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_definition);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_reference);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_reference);
      if (lookahead == 's') ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_reference);
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_reference);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_implements);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_implements);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_type_defines);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_type_defines);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_references);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_references);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_relationships);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_relationships);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_defined_by);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_defined_by);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(166);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_POUNDdocstring_COLON);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_') ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'a') ADVANCE(161);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'b') ADVANCE(164);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'c') ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'c') ADVANCE(115);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'd') ADVANCE(103);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'd') ADVANCE(122);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(126);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(155);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(84);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(86);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(141);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(143);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(108);
      if (lookahead == 'i') ADVANCE(163);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(146);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(159);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(149);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(128);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(156);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(129);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(130);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'f') ADVANCE(132);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'f') ADVANCE(112);
      if (lookahead == 'l') ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'f') ADVANCE(135);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'f') ADVANCE(136);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'f') ADVANCE(123);
      if (lookahead == 'l') ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'h') ADVANCE(134);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'i') ADVANCE(142);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'i') ADVANCE(150);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'i') ADVANCE(154);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'i') ADVANCE(148);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'i') ADVANCE(147);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'i') ADVANCE(151);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'i') ADVANCE(163);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'l') ADVANCE(116);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'm') ADVANCE(152);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'm') ADVANCE(119);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(118);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(157);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(82);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(162);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(138);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(120);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(107);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'o') ADVANCE(144);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'o') ADVANCE(145);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'p') ADVANCE(139);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'p') ADVANCE(113);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'p') ADVANCE(160);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'r') ADVANCE(117);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'r') ADVANCE(121);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(131);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(90);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(94);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 't') ADVANCE(133);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 't') ADVANCE(158);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 't') ADVANCE(137);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'y') ADVANCE(96);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'y') ADVANCE(153);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(166);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'l') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'w') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '_') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_forward_definition);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 78},
  [2] = {.lex_state = 79},
  [3] = {.lex_state = 79},
  [4] = {.lex_state = 79},
  [5] = {.lex_state = 79},
  [6] = {.lex_state = 79},
  [7] = {.lex_state = 79},
  [8] = {.lex_state = 79},
  [9] = {.lex_state = 79},
  [10] = {.lex_state = 78},
  [11] = {.lex_state = 78},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 76},
  [14] = {.lex_state = 79},
  [15] = {.lex_state = 79},
  [16] = {.lex_state = 79},
  [17] = {.lex_state = 79},
  [18] = {.lex_state = 79},
  [19] = {.lex_state = 79},
  [20] = {.lex_state = 79},
  [21] = {.lex_state = 79},
  [22] = {.lex_state = 77},
  [23] = {.lex_state = 78},
  [24] = {.lex_state = 75},
  [25] = {.lex_state = 78},
  [26] = {.lex_state = 78},
  [27] = {.lex_state = 78},
  [28] = {.lex_state = 78},
  [29] = {.lex_state = 78},
  [30] = {.lex_state = 78},
  [31] = {.lex_state = 75},
  [32] = {.lex_state = 75},
  [33] = {.lex_state = 75},
  [34] = {.lex_state = 75},
  [35] = {.lex_state = 75},
  [36] = {.lex_state = 75},
  [37] = {.lex_state = 75},
  [38] = {.lex_state = 75},
  [39] = {.lex_state = 75},
  [40] = {.lex_state = 75},
  [41] = {.lex_state = 75},
  [42] = {.lex_state = 99},
  [43] = {.lex_state = 99},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 78},
  [46] = {.lex_state = 78},
  [47] = {.lex_state = 75},
  [48] = {.lex_state = 75},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_definition] = ACTIONS(1),
    [anon_sym_reference] = ACTIONS(1),
    [sym_forward_definition] = ACTIONS(1),
    [anon_sym_implements] = ACTIONS(1),
    [anon_sym_type_defines] = ACTIONS(1),
    [anon_sym_references] = ACTIONS(1),
    [anon_sym_relationships] = ACTIONS(1),
    [anon_sym_defined_by] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUNDdocstring_COLON] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(44),
    [sym__statement] = STATE(10),
    [sym_definition_statement] = STATE(10),
    [sym_reference_statement] = STATE(10),
    [sym_relationships_statement] = STATE(10),
    [sym_comment] = STATE(10),
    [sym_docstring] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_definition] = ACTIONS(5),
    [anon_sym_reference] = ACTIONS(7),
    [anon_sym_relationships] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_POUNDdocstring_COLON] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__definition_relations] = STATE(3),
    [sym_implements] = STATE(3),
    [sym_type_defines] = STATE(3),
    [sym_references] = STATE(3),
    [sym__all_relations] = STATE(3),
    [sym_defined_by] = STATE(3),
    [aux_sym_relationships_statement_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_definition] = ACTIONS(15),
    [anon_sym_reference] = ACTIONS(17),
    [anon_sym_implements] = ACTIONS(19),
    [anon_sym_type_defines] = ACTIONS(21),
    [anon_sym_references] = ACTIONS(23),
    [anon_sym_relationships] = ACTIONS(15),
    [anon_sym_defined_by] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_POUNDdocstring_COLON] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__definition_relations] = STATE(4),
    [sym_implements] = STATE(4),
    [sym_type_defines] = STATE(4),
    [sym_references] = STATE(4),
    [sym__all_relations] = STATE(4),
    [sym_defined_by] = STATE(4),
    [aux_sym_relationships_statement_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_definition] = ACTIONS(27),
    [anon_sym_reference] = ACTIONS(29),
    [anon_sym_implements] = ACTIONS(19),
    [anon_sym_type_defines] = ACTIONS(21),
    [anon_sym_references] = ACTIONS(23),
    [anon_sym_relationships] = ACTIONS(27),
    [anon_sym_defined_by] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(29),
    [anon_sym_POUNDdocstring_COLON] = ACTIONS(27),
  },
  [STATE(4)] = {
    [sym__definition_relations] = STATE(4),
    [sym_implements] = STATE(4),
    [sym_type_defines] = STATE(4),
    [sym_references] = STATE(4),
    [sym__all_relations] = STATE(4),
    [sym_defined_by] = STATE(4),
    [aux_sym_relationships_statement_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_definition] = ACTIONS(31),
    [anon_sym_reference] = ACTIONS(33),
    [anon_sym_implements] = ACTIONS(35),
    [anon_sym_type_defines] = ACTIONS(38),
    [anon_sym_references] = ACTIONS(41),
    [anon_sym_relationships] = ACTIONS(31),
    [anon_sym_defined_by] = ACTIONS(44),
    [anon_sym_POUND] = ACTIONS(33),
    [anon_sym_POUNDdocstring_COLON] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(51), 1,
      anon_sym_implements,
    ACTIONS(53), 1,
      anon_sym_type_defines,
    ACTIONS(55), 1,
      anon_sym_references,
    ACTIONS(49), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(47), 4,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
    STATE(6), 5,
      sym__definition_relations,
      sym_implements,
      sym_type_defines,
      sym_references,
      aux_sym_definition_statement_repeat1,
  [27] = 6,
    ACTIONS(51), 1,
      anon_sym_implements,
    ACTIONS(53), 1,
      anon_sym_type_defines,
    ACTIONS(55), 1,
      anon_sym_references,
    ACTIONS(59), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
    STATE(7), 5,
      sym__definition_relations,
      sym_implements,
      sym_type_defines,
      sym_references,
      aux_sym_definition_statement_repeat1,
  [54] = 6,
    ACTIONS(65), 1,
      anon_sym_implements,
    ACTIONS(68), 1,
      anon_sym_type_defines,
    ACTIONS(71), 1,
      anon_sym_references,
    ACTIONS(63), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(61), 4,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
    STATE(7), 5,
      sym__definition_relations,
      sym_implements,
      sym_type_defines,
      sym_references,
      aux_sym_definition_statement_repeat1,
  [81] = 6,
    ACTIONS(51), 1,
      anon_sym_implements,
    ACTIONS(53), 1,
      anon_sym_type_defines,
    ACTIONS(55), 1,
      anon_sym_references,
    ACTIONS(76), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
    STATE(9), 5,
      sym__definition_relations,
      sym_implements,
      sym_type_defines,
      sym_references,
      aux_sym_definition_statement_repeat1,
  [108] = 6,
    ACTIONS(51), 1,
      anon_sym_implements,
    ACTIONS(53), 1,
      anon_sym_type_defines,
    ACTIONS(55), 1,
      anon_sym_references,
    ACTIONS(80), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(78), 4,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
    STATE(7), 5,
      sym__definition_relations,
      sym_implements,
      sym_type_defines,
      sym_references,
      aux_sym_definition_statement_repeat1,
  [135] = 8,
    ACTIONS(5), 1,
      anon_sym_definition,
    ACTIONS(7), 1,
      anon_sym_reference,
    ACTIONS(9), 1,
      anon_sym_relationships,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_POUNDdocstring_COLON,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    STATE(45), 1,
      sym_docstring,
    STATE(11), 6,
      sym__statement,
      sym_definition_statement,
      sym_reference_statement,
      sym_relationships_statement,
      sym_comment,
      aux_sym_source_file_repeat1,
  [165] = 8,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      anon_sym_definition,
    ACTIONS(89), 1,
      anon_sym_reference,
    ACTIONS(92), 1,
      anon_sym_relationships,
    ACTIONS(95), 1,
      anon_sym_POUND,
    ACTIONS(98), 1,
      anon_sym_POUNDdocstring_COLON,
    STATE(45), 1,
      sym_docstring,
    STATE(11), 6,
      sym__statement,
      sym_definition_statement,
      sym_reference_statement,
      sym_relationships_statement,
      sym_comment,
      aux_sym_source_file_repeat1,
  [195] = 3,
    ACTIONS(103), 1,
      sym_name,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_POUNDdocstring_COLON,
    ACTIONS(105), 8,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUND,
  [213] = 3,
    ACTIONS(103), 1,
      sym_name,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_POUNDdocstring_COLON,
    ACTIONS(105), 7,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_POUND,
  [230] = 2,
    ACTIONS(109), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(107), 8,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUNDdocstring_COLON,
  [245] = 2,
    ACTIONS(113), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(111), 8,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUNDdocstring_COLON,
  [260] = 2,
    ACTIONS(117), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUNDdocstring_COLON,
  [275] = 2,
    ACTIONS(121), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUNDdocstring_COLON,
  [290] = 2,
    ACTIONS(125), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(123), 8,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUNDdocstring_COLON,
  [305] = 2,
    ACTIONS(129), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(127), 8,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUNDdocstring_COLON,
  [320] = 2,
    ACTIONS(133), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(131), 8,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUNDdocstring_COLON,
  [335] = 2,
    ACTIONS(137), 2,
      anon_sym_reference,
      anon_sym_POUND,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_implements,
      anon_sym_type_defines,
      anon_sym_references,
      anon_sym_relationships,
      anon_sym_defined_by,
      anon_sym_POUNDdocstring_COLON,
  [350] = 3,
    ACTIONS(139), 1,
      sym_name,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_POUNDdocstring_COLON,
    ACTIONS(105), 4,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_relationships,
      anon_sym_POUND,
  [364] = 2,
    ACTIONS(117), 1,
      anon_sym_POUND,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
  [375] = 6,
    ACTIONS(141), 1,
      sym_name,
    ACTIONS(143), 1,
      sym_forward_definition,
    ACTIONS(145), 1,
      anon_sym_local,
    STATE(26), 1,
      sym_identifier,
    STATE(29), 1,
      sym_global_identifier,
    STATE(30), 1,
      sym_local_identifier,
  [394] = 2,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
  [405] = 2,
    ACTIONS(153), 1,
      anon_sym_POUND,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
  [416] = 2,
    ACTIONS(157), 1,
      anon_sym_POUND,
    ACTIONS(155), 5,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
  [427] = 2,
    ACTIONS(121), 1,
      anon_sym_POUND,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
  [438] = 2,
    ACTIONS(109), 1,
      anon_sym_POUND,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
  [449] = 2,
    ACTIONS(113), 1,
      anon_sym_POUND,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_definition,
      anon_sym_reference,
      anon_sym_relationships,
      anon_sym_POUNDdocstring_COLON,
  [460] = 5,
    ACTIONS(159), 1,
      sym_name,
    ACTIONS(161), 1,
      anon_sym_local,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
    STATE(18), 1,
      sym_identifier,
  [476] = 5,
    ACTIONS(159), 1,
      sym_name,
    ACTIONS(161), 1,
      anon_sym_local,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
    STATE(20), 1,
      sym_identifier,
  [492] = 5,
    ACTIONS(159), 1,
      sym_name,
    ACTIONS(161), 1,
      anon_sym_local,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
    STATE(21), 1,
      sym_identifier,
  [508] = 5,
    ACTIONS(161), 1,
      anon_sym_local,
    ACTIONS(163), 1,
      sym_name,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
    STATE(19), 1,
      sym_identifier,
  [524] = 5,
    ACTIONS(161), 1,
      anon_sym_local,
    ACTIONS(163), 1,
      sym_name,
    STATE(2), 1,
      sym_identifier,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
  [540] = 5,
    ACTIONS(141), 1,
      sym_name,
    ACTIONS(145), 1,
      anon_sym_local,
    STATE(25), 1,
      sym_identifier,
    STATE(29), 1,
      sym_global_identifier,
    STATE(30), 1,
      sym_local_identifier,
  [556] = 5,
    ACTIONS(159), 1,
      sym_name,
    ACTIONS(161), 1,
      anon_sym_local,
    STATE(8), 1,
      sym_identifier,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
  [572] = 5,
    ACTIONS(161), 1,
      anon_sym_local,
    ACTIONS(163), 1,
      sym_name,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
    STATE(21), 1,
      sym_identifier,
  [588] = 5,
    ACTIONS(159), 1,
      sym_name,
    ACTIONS(161), 1,
      anon_sym_local,
    STATE(5), 1,
      sym_identifier,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
  [604] = 5,
    ACTIONS(161), 1,
      anon_sym_local,
    ACTIONS(163), 1,
      sym_name,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
    STATE(18), 1,
      sym_identifier,
  [620] = 5,
    ACTIONS(161), 1,
      anon_sym_local,
    ACTIONS(163), 1,
      sym_name,
    STATE(14), 1,
      sym_global_identifier,
    STATE(15), 1,
      sym_local_identifier,
    STATE(20), 1,
      sym_identifier,
  [636] = 1,
    ACTIONS(165), 1,
      aux_sym_comment_token1,
  [640] = 1,
    ACTIONS(167), 1,
      aux_sym_comment_token1,
  [644] = 1,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
  [648] = 1,
    ACTIONS(171), 1,
      anon_sym_definition,
  [652] = 1,
    ACTIONS(173), 1,
      anon_sym_definition,
  [656] = 1,
    ACTIONS(175), 1,
      sym_name,
  [660] = 1,
    ACTIONS(177), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 27,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 81,
  [SMALL_STATE(9)] = 108,
  [SMALL_STATE(10)] = 135,
  [SMALL_STATE(11)] = 165,
  [SMALL_STATE(12)] = 195,
  [SMALL_STATE(13)] = 213,
  [SMALL_STATE(14)] = 230,
  [SMALL_STATE(15)] = 245,
  [SMALL_STATE(16)] = 260,
  [SMALL_STATE(17)] = 275,
  [SMALL_STATE(18)] = 290,
  [SMALL_STATE(19)] = 305,
  [SMALL_STATE(20)] = 320,
  [SMALL_STATE(21)] = 335,
  [SMALL_STATE(22)] = 350,
  [SMALL_STATE(23)] = 364,
  [SMALL_STATE(24)] = 375,
  [SMALL_STATE(25)] = 394,
  [SMALL_STATE(26)] = 405,
  [SMALL_STATE(27)] = 416,
  [SMALL_STATE(28)] = 427,
  [SMALL_STATE(29)] = 438,
  [SMALL_STATE(30)] = 449,
  [SMALL_STATE(31)] = 460,
  [SMALL_STATE(32)] = 476,
  [SMALL_STATE(33)] = 492,
  [SMALL_STATE(34)] = 508,
  [SMALL_STATE(35)] = 524,
  [SMALL_STATE(36)] = 540,
  [SMALL_STATE(37)] = 556,
  [SMALL_STATE(38)] = 572,
  [SMALL_STATE(39)] = 588,
  [SMALL_STATE(40)] = 604,
  [SMALL_STATE(41)] = 620,
  [SMALL_STATE(42)] = 636,
  [SMALL_STATE(43)] = 640,
  [SMALL_STATE(44)] = 644,
  [SMALL_STATE(45)] = 648,
  [SMALL_STATE(46)] = 652,
  [SMALL_STATE(47)] = 656,
  [SMALL_STATE(48)] = 660,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationships_statement, 2, 0, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationships_statement, 2, 0, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationships_statement, 3, 0, 5),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationships_statement, 3, 0, 5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_relationships_statement_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_relationships_statement_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_relationships_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_relationships_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_relationships_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_relationships_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_statement, 2, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_definition_statement, 2, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_statement, 3, 0, 5),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_definition_statement, 3, 0, 5),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_definition_statement_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_definition_statement_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_statement, 3, 0, 7),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_definition_statement, 3, 0, 7),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition_statement, 4, 0, 8),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_definition_statement, 4, 0, 8),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_identifier, 2, 0, 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_local_identifier, 2, 0, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global_identifier, 2, 0, 4),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global_identifier, 2, 0, 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_defines, 2, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_defines, 2, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defined_by, 2, 0, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defined_by, 2, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implements, 2, 0, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_implements, 2, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_references, 2, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_references, 2, 0, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference_statement, 3, 0, 6),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference_statement, 3, 0, 6),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference_statement, 2, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference_statement, 2, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [169] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docstring, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_reprolang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
